/**
 * Output sanitizer for DeepSeek streaming responses.
 * Removes leaked internal markers, role prefixes, and post-tool hallucinations.
 *
 * Ported from:
 * - deepseek-free-api: sanitize_leaked_output (DeepSeek native markers)
 * - ds-free-api: is_inside_code_fence (code fence detection)
 */

// ─── DeepSeek Native Markers ─────────────────────────────────────────────────
// The model sometimes leaks internal conversation markers in its output.
// These use both ASCII and Unicode variants (｜ U+FF5C, ▁ U+2581).

const LEAKED_BOS_MARKER = /(?:<[｜|]\s*begin[_▁]of[_▁]sentence\s*[｜|]>)/gi
const LEAKED_META_MARKERS = /(?:<[｜|]\s*(?:assistant|user|tool|system|end[_▁]of[_▁]sentence|end[_▁]of[_▁]thinking|end[_▁]of[_▁]toolresults|end[_▁]of[_▁]instructions)\s*[｜|]>)/gi

// ─── Role Prefix Patterns ────────────────────────────────────────────────────
// The model echoes back role prefixes from the prompt format.

const ROLE_PREFIX_PATTERN = /^(Assistant|User|Response|Tool Response\s*\([^)]*\)):\s*/gm

// ─── AI Disclaimer Patterns ──────────────────────────────────────────────────

const AI_DISCLAIMER_PATTERNS = [
  /\n*\*?\s*Esta resposta é gerada por IA[^]*$/i,
  /\n*\*?\s*This response is generated by AI[^]*$/i,
  /\n*\*?\s*Gerado por IA[^]*$/i,
  /\n*\*?\s*Generated by AI[^]*$/i,
  /\n*\*?\s*Gerado por AI[^]*$/i,
  /\n*---\s*\n\*?Esta resposta[^]*$/i,
  /\n*\*?\s*Gerado por AI,?\s*apenas para refer[eê]ncia[^]*$/i,
  /\n*\*?\s*Generated by AI,?\s*for reference only[^]*$/i,
  /\n*\*?\s*AI-generated,?\s*for reference only[^]*$/i,
]

// ─── Citation Tags ───────────────────────────────────────────────────────────
// DeepSeek web search leaves citation markers in output.

const CITATION_PATTERN = /\[citation:\d+\]/g

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Full sanitization pipeline for text before showing to user.
 * Apply to final/trailing buffer (not mid-stream chunks to avoid breaking words).
 */
export function sanitizeOutput(text: string): string {
  if (!text) return text

  let result = text

  // Remove DeepSeek native markers
  result = result.replace(LEAKED_BOS_MARKER, '')
  result = result.replace(LEAKED_META_MARKERS, '')

  // Remove role prefixes
  result = result.replace(ROLE_PREFIX_PATTERN, '')

  // Remove citation tags
  result = result.replace(CITATION_PATTERN, '')

  // Remove AI disclaimers (check from end of text)
  for (const pattern of AI_DISCLAIMER_PATTERNS) {
    const match = result.match(pattern)
    if (match && match.index !== undefined) {
      result = result.slice(0, match.index).trimEnd()
      break
    }
  }

  // Collapse excessive newlines
  result = result.replace(/\n{4,}/g, '\n\n\n')

  return result
}

// ─── Stream-safe Role Prefix Pattern ────────────────────────────────────────
// Simpler pattern for streaming: only removes prefixes at the very start of
// the chunk or immediately after a newline. Safe because these prefixes are
// self-contained tokens that won't split across chunk boundaries.

const STREAM_ROLE_PREFIX = /(?:^|\n)(Assistant|User|Response|Tool Response\s*\([^)]*\)):\s*/g

/**
 * Light sanitization for streaming chunks (mid-stream).
 * Only removes markers that can be detected in partial text without
 * risking breaking words across chunk boundaries.
 */
export function sanitizeStreamChunk(text: string): string {
  if (!text) return text

  let result = text

  // Remove DeepSeek native markers (self-contained, safe to remove mid-stream)
  result = result.replace(LEAKED_BOS_MARKER, '')
  result = result.replace(LEAKED_META_MARKERS, '')

  // Remove role prefixes at start of text or after newlines
  result = result.replace(STREAM_ROLE_PREFIX, (match, _role, offset) => {
    // Preserve the leading newline if the match started after one
    return offset > 0 && match.startsWith('\n') ? '\n' : ''
  })

  // Remove citation tags
  result = result.replace(CITATION_PATTERN, '')

  return result
}

// ─── Code Fence Detection ────────────────────────────────────────────────────
// Ported from ds-free-api: prevents parsing tool calls inside code blocks.

/**
 * Check if a position in text is inside an unclosed code fence (```).
 * Used to avoid false-positive tool call detection in code examples.
 */
export function isInsideCodeFence(text: string, position: number): boolean {
  const before = text.slice(0, position)
  const fenceCount = (before.match(/```/g) || []).length
  return fenceCount % 2 === 1
}

// ─── Tool Name Resolution ────────────────────────────────────────────────────
// Strict resolution: exact match, case-insensitive, case conversions, and
// known DeepSeek hallucination mappings. No partial/prefix matching.

const DEEPSEEK_HALLUCINATION_MAP: Record<string, string> = {
  execute_command: 'shell',
  run_command: 'shell',
  execute: 'shell',
  file_read: 'read_file',
  file_write: 'write_file',
  list_directory: 'read_folder',
  search_files: 'grep',
}

/**
 * Resolve a tool name against a list of known tools.
 * Handles: exact match, case-insensitive exact match, camelCase↔snake_case
 * exact conversions, and known DeepSeek hallucination mappings.
 * No partial or prefix matching is performed.
 */
export function resolveToolName(name: string, knownTools: string[]): string | null {
  if (!name || !knownTools.length) return null

  // 1. Exact match
  if (knownTools.includes(name)) return name

  // 2. Case-insensitive exact match
  const lower = name.toLowerCase()
  const ciMatch = knownTools.find((t) => t.toLowerCase() === lower)
  if (ciMatch) return ciMatch

  // 3. camelCase/PascalCase → snake_case (exact match after conversion)
  const snake = name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()
  if (snake !== lower) {
    if (knownTools.includes(snake)) return snake
    const snakeCI = knownTools.find((t) => t.toLowerCase() === snake)
    if (snakeCI) return snakeCI
  }

  // 4. snake_case → camelCase (exact match after conversion)
  const camel = name.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
  if (camel !== name) {
    const camelLower = camel.toLowerCase()
    const camelMatch = knownTools.find((t) => t.toLowerCase() === camelLower)
    if (camelMatch) return camelMatch
  }

  // 5. Known DeepSeek hallucination mappings
  const mapped = DEEPSEEK_HALLUCINATION_MAP[lower]
  if (mapped) {
    if (knownTools.includes(mapped)) return mapped
    const mappedCI = knownTools.find((t) => t.toLowerCase() === mapped.toLowerCase())
    if (mappedCI) return mappedCI
  }

  return null
}
