/**
 * Output sanitizer for DeepSeek streaming responses.
 * Removes leaked internal markers, role prefixes, and post-tool hallucinations.
 *
 * Ported from:
 * - deepseek-free-api: sanitize_leaked_output (DeepSeek native markers)
 * - ds-free-api: is_inside_code_fence (code fence detection)
 */

// ─── DeepSeek Native Markers ─────────────────────────────────────────────────
// The model sometimes leaks internal conversation markers in its output.
// These use both ASCII and Unicode variants (｜ U+FF5C, ▁ U+2581).

const LEAKED_BOS_MARKER = /(?:<[｜|]\s*begin[_▁]of[_▁]sentence\s*[｜|]>)/gi
const LEAKED_META_MARKERS = /(?:<[｜|]\s*(?:assistant|user|tool|system|end[_▁]of[_▁]sentence|end[_▁]of[_▁]thinking|end[_▁]of[_▁]toolresults|end[_▁]of[_▁]instructions)\s*[｜|]>)/gi

// ─── Role Prefix Patterns ────────────────────────────────────────────────────
// The model echoes back role prefixes from the prompt format.

const ROLE_PREFIX_PATTERN = /^(Assistant|User|Response|Tool Response\s*\([^)]*\)):\s*/gm

// ─── AI Disclaimer Patterns ──────────────────────────────────────────────────

const AI_DISCLAIMER_PATTERNS = [
  /\n*\*?\s*Esta resposta é gerada por IA[^]*$/i,
  /\n*\*?\s*This response is generated by AI[^]*$/i,
  /\n*\*?\s*Gerado por IA[^]*$/i,
  /\n*\*?\s*Generated by AI[^]*$/i,
  /\n*\*?\s*Gerado por AI[^]*$/i,
  /\n*---\s*\n\*?Esta resposta[^]*$/i,
  /\n*\*?\s*Gerado por AI,?\s*apenas para refer[eê]ncia[^]*$/i,
  /\n*\*?\s*Generated by AI,?\s*for reference only[^]*$/i,
  /\n*\*?\s*AI-generated,?\s*for reference only[^]*$/i,
]

// ─── Citation Tags ───────────────────────────────────────────────────────────
// DeepSeek web search leaves citation markers in output.

const CITATION_PATTERN = /\[citation:\d+\]/g

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Full sanitization pipeline for text before showing to user.
 * Apply to final/trailing buffer (not mid-stream chunks to avoid breaking words).
 */
export function sanitizeOutput(text: string): string {
  if (!text) return text

  let result = text

  // Remove DeepSeek native markers
  result = result.replace(LEAKED_BOS_MARKER, '')
  result = result.replace(LEAKED_META_MARKERS, '')

  // Remove role prefixes
  result = result.replace(ROLE_PREFIX_PATTERN, '')

  // Remove citation tags
  result = result.replace(CITATION_PATTERN, '')

  // Remove AI disclaimers (check from end of text)
  for (const pattern of AI_DISCLAIMER_PATTERNS) {
    const match = result.match(pattern)
    if (match && match.index !== undefined) {
      result = result.slice(0, match.index).trimEnd()
      break
    }
  }

  // Collapse excessive newlines
  result = result.replace(/\n{4,}/g, '\n\n\n')

  return result
}

/**
 * Light sanitization for streaming chunks (mid-stream).
 * Only removes markers that can be detected in partial text without
 * risking breaking words across chunk boundaries.
 */
export function sanitizeStreamChunk(text: string): string {
  if (!text) return text

  let result = text

  // Remove DeepSeek native markers (self-contained, safe to remove mid-stream)
  result = result.replace(LEAKED_BOS_MARKER, '')
  result = result.replace(LEAKED_META_MARKERS, '')

  // Remove citation tags
  result = result.replace(CITATION_PATTERN, '')

  return result
}

// ─── Code Fence Detection ────────────────────────────────────────────────────
// Ported from ds-free-api: prevents parsing tool calls inside code blocks.

/**
 * Check if a position in text is inside an unclosed code fence (```).
 * Used to avoid false-positive tool call detection in code examples.
 */
export function isInsideCodeFence(text: string, position: number): boolean {
  const before = text.slice(0, position)
  const fenceCount = (before.match(/```/g) || []).length
  return fenceCount % 2 === 1
}

// ─── Tool Name Fuzzy Resolution ──────────────────────────────────────────────
// Ported from deepseek-free-api: handles case mismatches and naming variants.

/**
 * Resolve a tool name against a list of known tools.
 * Handles: exact match, case-insensitive, camelCase→snake_case conversion.
 */
export function resolveToolName(name: string, knownTools: string[]): string | null {
  if (!name || !knownTools.length) return null

  // Exact match
  if (knownTools.includes(name)) return name

  // Case-insensitive match
  const lower = name.toLowerCase()
  const ciMatch = knownTools.find((t) => t.toLowerCase() === lower)
  if (ciMatch) return ciMatch

  // camelCase/PascalCase → snake_case
  const snake = name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()
  if (knownTools.includes(snake)) return snake
  const snakeMatch = knownTools.find((t) => t.toLowerCase() === snake)
  if (snakeMatch) return snakeMatch

  // snake_case → camelCase
  const camel = name.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
  const camelMatch = knownTools.find((t) => t.toLowerCase() === camel.toLowerCase())
  if (camelMatch) return camelMatch

  return null
}
