/** Bundled with the CLI: no asset server, third-party scripts or credentials in browser storage. */
export const BOT_PANEL_HTML = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DeepSeek Pods</title>
<style nonce="__NONCE__">
:root{color-scheme:light;--canvas:#f2f5f9;--paper:#fff;--ink:#18283d;--muted:#657386;--line:#d7dfe9;--blue:#3457d5;--alert:#9b491c;font-family:"Trebuchet MS",Verdana,sans-serif;color:var(--ink);background:var(--canvas);font-size:15px}
*{box-sizing:border-box}body{margin:0}button,input,textarea,select{font:inherit}button{cursor:pointer;border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:7px;padding:9px 13px;min-height:40px}button:hover{border-color:var(--blue)}button:disabled{cursor:wait;opacity:.55}.primary{background:var(--blue);color:white;border-color:var(--blue)}.danger{color:var(--alert)}:focus-visible{outline:3px solid var(--blue);outline-offset:3px}input,textarea,select{width:100%;border:1px solid var(--line);border-radius:6px;background:var(--paper);color:var(--ink);padding:11px}textarea{resize:vertical;min-height:78px}label{display:block;font-size:14px;line-height:1.5;margin-bottom:12px}label input,label textarea,label select{margin-top:5px}h1,h2,h3,p{margin:0}h1{font-size:27px;line-height:1.2}h2{font-size:20px}h3{font-size:16px}p{line-height:1.6}.muted{color:var(--muted);font-size:14px}.row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.spread{justify-content:space-between}.stack{display:grid;gap:12px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:330px;overflow:auto;font:13px/1.6 "DejaVu Sans Mono",monospace;margin:12px 0}summary{cursor:pointer;line-height:1.6}details{margin-top:12px}time{font-size:12px;color:var(--muted)}[hidden]{display:none!important}
#notice{padding:12px 24px;background:#fff1e8;color:var(--alert);border-bottom:1px solid #ead3c0;line-height:1.5}#login{max-width:430px;margin:12vh auto;padding:28px}#login h1{margin:16px 0 10px}#login form{margin-top:24px}.brand{font-size:17px;font-weight:bold;letter-spacing:-.4px}.brand b{color:var(--blue)}#app{height:100dvh;display:grid;grid-template-rows:auto 1fr}.top{background:var(--paper);padding:16px 24px;border-bottom:1px solid var(--line)}.connection{color:var(--muted);font-size:13px}.connection::before{content:"";display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--blue);margin-right:8px}.layout{display:grid;grid-template-columns:230px minmax(300px,1fr) 330px;min-height:0}.rail{padding:24px 16px;border-right:1px solid var(--line);overflow:auto}.rail h2{font-size:15px;padding:0 10px;margin-bottom:14px}.bot{display:block;width:100%;text-align:left;background:transparent;border-color:transparent;margin-bottom:8px;padding:12px}.bot strong{display:block}.bot span{display:block;font-size:12px;color:var(--muted);margin-top:6px}.bot.selected{background:#e4eafc;border-color:#b5c4f3}.new{width:100%;margin-top:16px}.workspace{display:flex;flex-direction:column;min-height:0;background:var(--paper)}.heading{padding:26px 28px 20px;border-bottom:1px solid var(--line)}.heading p{margin-top:10px;max-width:65ch;overflow-wrap:anywhere}#feed{padding:0 28px;overflow:auto;flex:1}.empty{padding:36px 0;color:var(--muted);line-height:1.7}.turn{padding:24px 0;border-bottom:1px solid var(--line);overflow-wrap:anywhere}.prompt{font-weight:bold;margin:12px 0 16px;white-space:pre-wrap}.answer{white-space:pre-wrap;line-height:1.65;max-width:75ch}.badge{font-size:12px;border-radius:4px;padding:4px 7px;background:#edf1f7;color:var(--muted)}.badge.running{color:#2844aa;background:#e7ecfe}.badge.waiting,.badge.blocked,.badge.failed{background:#fff0df;color:var(--alert)}#composer{padding:16px 28px 20px;border-top:1px solid var(--line);background:var(--paper)}#composer label{margin-bottom:8px}#composer .row{margin-top:10px}.review{border-left:1px solid var(--line);padding:24px 20px;overflow:auto}.review section+section{margin-top:32px}.review h2{font-size:17px;margin-bottom:16px}.decision{padding:16px 0;border-top:2px solid #d6a971}.decision pre{background:#fff;padding:12px;border:1px solid var(--line);border-radius:6px}.routine,.note{padding:14px 0;border-bottom:1px solid var(--line);font-size:14px}.routine p,.note p{margin-top:5px;overflow-wrap:anywhere}#activity-list{font-size:13px;line-height:1.6}#activity-list>div{padding:12px 0;border-bottom:1px solid var(--line)}dialog{border:1px solid var(--line);border-radius:12px;padding:26px;width:min(540px,calc(100% - 28px));max-height:90dvh;color:var(--ink)}dialog::backdrop{background:rgba(24,40,61,.35)}dialog h2{margin-bottom:20px}.error{color:var(--alert);line-height:1.5;margin-top:10px}
@media(max-width:1150px){.layout{grid-template-columns:190px minmax(280px,1fr) 280px}.heading,#feed,#composer{padding-left:20px;padding-right:20px}.review{padding:20px 16px}}
@media(max-width:850px){#app{height:auto;min-height:100dvh}.top{padding:14px 16px}.layout{display:flex;flex-direction:column}.rail{padding:14px 12px;border-right:0;border-bottom:1px solid var(--line)}.rail h2{display:none}#bots{display:flex;overflow:auto;gap:6px}.bot{width:auto;min-width:140px;margin:0}.new{width:auto;margin:12px 0 0}.review{order:1;border-left:0;border-top:1px solid var(--line);padding:22px 20px}.workspace{min-height:450px}.heading{padding-top:22px}#feed{overflow:visible}#composer{position:sticky;bottom:0;z-index:1;box-shadow:0 -6px 15px rgba(24,40,61,.04)}#login{margin:6vh auto}#notice{padding:12px 16px}.connection{display:none}}
@media(prefers-reduced-motion:no-preference){button{transition:border-color .15s,background .15s}}.review input[type=checkbox]{width:auto;margin-right:8px}
#browser-dialog{width:min(1100px,calc(100% - 28px))}#browser-image{display:block;width:100%;height:auto;margin:18px 0;border:1px solid var(--line);border-radius:6px}#browser-navigation,#browser-text{display:grid;grid-template-columns:1fr auto;align-items:end;gap:10px;margin-top:18px}#browser-navigation label,#browser-text label{margin:0}
.group-messages{max-height:48dvh;overflow:auto;border:1px solid var(--line);border-radius:8px;padding:12px}.group-message{padding:12px 0;border-bottom:1px solid var(--line);white-space:pre-wrap;overflow-wrap:anywhere}.group-message:last-child{border-bottom:0}.group-members{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0}.group-members input[type=checkbox]{width:auto;margin-right:6px}
</style></head><body>
<div id="notice" role="alert" hidden></div>
<section id="login"><div class="brand">DeepSeek <b>Pods</b></div><h1>Keep your agents close.</h1><p class="muted">Sign in to follow their work, send tasks and review requests.</p><form id="login-form"><label>Access token<input id="token" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">Sign in</button><p id="login-error" class="error" role="alert"></p></form></section>
<div id="app" hidden><header class="top row spread"><div class="brand">DeepSeek <b>Pods</b></div><div class="row"><span id="connection" class="connection">Supervisor connected</span><button id="logout">Sign out</button></div></header>
<div class="layout"><nav class="rail" aria-label="Your agents"><h2>Your agents</h2><div id="bots"></div><button id="new-bot" class="new">Create agent</button><h2>Collaboration rooms</h2><div id="group-list"></div><button id="new-group" class="new">Create group</button></nav>
<main class="workspace"><header class="heading"><div class="row spread"><h1 id="bot-name">Your agents</h1><button id="toggle-bot" hidden>Pause new work</button></div><p id="responsibility" class="muted">Create an agent with a project and a responsibility to get started.</p></header><div id="feed" aria-label="Conversation"></div>
<form id="composer" hidden><label for="message">Send a task</label><textarea id="message" required maxlength="100000" placeholder="What should this agent work on?"></textarea><div class="row spread"><span class="muted">You can leave after sending. Work stays in the queue.</span><button type="submit" class="primary">Send task</button></div></form></main>
<aside class="review" aria-label="Review and routines"><section><h2>Needs your attention</h2><div id="decisions"><p class="muted">Requests for approval appear here.</p></div></section><section id="history-section" hidden><h2>Search task history</h2><form id="history-search-form"><label>Search this agent's past tasks<input name="query" minlength="2" maxlength="128" required placeholder="A phrase or identifier"></label><button type="submit">Search</button><p class="error" role="alert"></p></form><div id="history-results"></div></section><section><div class="row spread"><h2>Routines</h2><button id="new-routine" hidden>Add routine</button></div><div id="routines"></div></section><section><h2>Learned browser skills</h2><div id="procedures"></div></section><section><div class="row spread"><h2>Memory</h2><button id="new-note">Add note</button></div><div id="notes"></div></section><section><h2>Data and privacy</h2><p class="muted">Export includes this agent's saved work and activity. Browser cookies, provider credentials and private browser profile files are excluded.</p><div class="actions"><button id="export-bot" hidden>Export data</button><button id="delete-bot" class="danger" hidden>Delete agent</button></div></section><section><div class="row spread"><h2>External delivery</h2><button id="new-delivery" hidden>Add webhook</button></div><p class="muted">Signed HTTPS notifications are sent when a selected task finishes. The receiver must verify the Ed25519 signature.</p><div id="deliveries"></div></section><details id="activity"><summary>Tool activity</summary><div id="activity-list"></div></details></aside>
</div></div>
<dialog id="browser-dialog"><div class="row spread"><h2>Codimium</h2><button type="button" data-close>Close view</button></div><p id="browser-state" class="muted"></p><div class="actions"><button id="browser-take">Take over</button><button id="browser-release">Return to agent</button><button id="browser-refresh">Refresh view</button></div><form id="browser-navigation"><label>Go to a page<input id="browser-url" type="url" required placeholder="https://example.com"></label><button type="submit">Navigate</button></form><img id="browser-image" alt="Current Codimium browser page" tabindex="0" hidden><p class="muted">Click the page to focus a field. Browser actions pause while you have control.</p><form id="browser-text"><label>Text to enter in the focused field<input id="browser-input" type="password" autocomplete="off" maxlength="16000" required></label><button type="submit">Send text to browser</button></form><div class="actions"><label>Key<select id="browser-key"><option>Enter</option><option>Tab</option><option>Backspace</option><option>Escape</option><option>ArrowDown</option><option>ArrowUp</option></select></label><button id="browser-press">Press key</button><button id="browser-up">Scroll up</button><button id="browser-down">Scroll down</button><button id="browser-accept">Accept dialog</button><button id="browser-dismiss">Dismiss dialog</button></div><label>Tab<select id="browser-tab"></select></label><p class="muted">Typed text is cleared after sending. It is never added to the agent's conversation or tool logs.</p></dialog>
<dialog id="create-dialog"><form id="create-form"><h2>Create agent</h2><label>Name<input name="name" required maxlength="64" pattern="[a-zA-Z0-9][a-zA-Z0-9_-]*" placeholder="engineer"></label><label>Project folder on the worker host<input name="projectRoot" required placeholder="/home/you/project"></label><label>Responsibility<textarea name="instructions" required placeholder="Maintain this project and report observed results."></textarea></label><label>Agent configuration (optional)<input name="agentConfig" placeholder="Existing configuration name"></label><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Create agent</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="note-dialog"><form id="note-form"><h2>Edit saved memory</h2><label>Saved fact<textarea name="content" required maxlength="10000"></textarea></label><label>Source<input name="source" required maxlength="4096" placeholder="Where this fact was confirmed"></label><label>Expires at (optional)<input name="expiresAt" type="datetime-local" step="0.001"></label><p class="muted">Notes are references, never permission grants. Updates affect new proposals; actions already started may finish. Removing a note removes current saved memory; conversation and activity history stay available.</p><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Save note</button><button type="button" id="remove-note" class="danger" hidden>Remove note</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="guide-dialog"><form id="guide-form"><h2>Guide this active task</h2><p class="muted">The agent will reconsider its next steps. Actions already started may finish; stop the task if you need to interrupt it.</p><label>Your correction<textarea name="message" required maxlength="100000" placeholder="What should change in the current task?"></textarea></label><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Send guidance</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="learn-dialog"><form id="learn-form"><h2>Learn this browser procedure</h2><p class="muted">Reuse the observed steps with new inputs. Each execution checks the current page. A changed page pauses the routine for review.</p><label>Skill name<input name="name" required maxlength="64" pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="prepare-daily-report"></label><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Save skill</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="routine-dialog"><form id="routine-form"><h2 id="routine-title">Add routine</h2><label>Name<input name="name" required maxlength="128"></label><label>Task<textarea name="prompt" required maxlength="10000"></textarea></label><label>Browser skill<select name="procedureId"><option value="">No browser skill</option></select></label><div id="procedure-inputs"></div><label>Schedule<select name="kind"><option value="daily">Every day</option><option value="interval">At an interval</option><option value="once">Once</option><option value="event">When an event arrives</option></select></label><div data-schedule="daily"><label>Time<input name="time" type="time" value="08:00"></label><label>Time zone<input name="timeZone" placeholder="America/Fortaleza"></label></div><div data-schedule="interval" hidden><label>Every (minutes)<input name="minutes" type="number" min="1" max="525600" value="60"></label></div><div data-schedule="once" hidden><label>Local date and time<input name="at" type="datetime-local"></label></div><div data-schedule="event" hidden><label>Event topic<input name="topic" placeholder="issue-created"></label></div><div data-schedule="recurring" hidden><label>Runs through (optional, your local time)<input name="endsAt" type="datetime-local" step="0.001"></label></div><p class="muted">Changes apply to future occurrences. Work already queued keeps its original instructions.</p><p class="error" role="alert"></p><div class="actions"><button id="routine-submit" type="submit" class="primary">Add routine</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="delivery-dialog"><form id="delivery-form"><h2>Add signed webhook</h2><label>HTTPS receiver URL<input name="url" type="url" required maxlength="2048" placeholder="https://example.com/hooks/deepseek"></label><p class="muted">Use a public host on port 443. Query strings and URL credentials are not accepted. Private signing keys stay on the worker host.</p><label><input name="topics" type="checkbox" value="run.completed" checked> Completed tasks</label><label><input name="topics" type="checkbox" value="run.failed" checked> Failed tasks</label><label><input name="topics" type="checkbox" value="run.blocked" checked> Tasks blocked for review</label><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Add webhook</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="group-create-dialog"><form id="group-create-form"><h2>Create collaboration group</h2><label>Group name<input name="name" maxlength="64" required></label><p class="muted">Select at least two enabled agents. Group messages and artifacts are shared with all selected agents.</p><div id="group-create-members" class="group-members"></div><label><input name="shareBrowser" type="checkbox"> Share this group's Codimium browser profile and cookies. Only one group task can use the browser at a time.</label><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Create group</button><button type="button" data-close>Cancel</button></div></form></dialog>
<dialog id="group-dialog"><h2 id="group-title">Collaboration group</h2><p id="group-description" class="muted"></p><div id="group-transcript" class="group-messages" aria-live="polite"></div><h3>Shared artifacts</h3><div id="group-artifacts"></div><form id="group-message-form"><div id="group-recipients" class="group-members"></div><label>Send a group task<textarea name="message" required maxlength="100000"></textarea></label><p class="muted">Private notes, provider credentials and browser cookies stay separate unless the group explicitly shares its browser.</p><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Send to selected agents</button><button type="button" data-close>Close</button><button type="button" id="delete-group" class="danger">Delete group</button></div></form></dialog>
<dialog id="reconcile-dialog"><form id="reconcile-form"><h2>Review interrupted work</h2><p class="muted">Inspect the effects on the worker host before continuing. A task may have acted before it stopped.</p><label>What did you verify?<textarea name="evidence" required maxlength="10000" placeholder="Describe the effects you observed and why continuing is safe."></textarea></label><p class="error" role="alert"></p><div class="actions"><button type="submit" class="primary">Save review</button><button type="button" data-close>Cancel</button></div></form></dialog>
<script nonce="__NONCE__">
const $ = id => document.getElementById(id);
let guideRun = null, guideKey = null, noteEdit = null, routineEdit = null;
let selected = null, current = null, selectedGroup = null, groupMessageKey = null, botsState = [], authenticated = false, refreshing = false, messageKey = null, routineKey = null, reviewRun = null, learnRun = null, eventCursor = 0, eventItems = [], browserRun = null, browserView = null, authEpoch = 0;
const signatures = new Map();
const drafts = new Map();
const routineRunKeys = new Map();
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=String(text);if(className)el.className=className;return el}
function submitter(event){return event.submitter||event.currentTarget.querySelector('button[type="submit"],button:not([type])')}
function button(text,action,className){const el=node('button',text,className);el.type='button';el.addEventListener('click',()=>perform(el,action));return el}
function notify(message){$('notice').textContent=message;$('notice').hidden=!message}
async function api(path,data){const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),credentials:'same-origin'});const value=await response.json();if(!response.ok){if(response.status===401)signOut();throw new Error(value.error||'Request failed')}return value}
async function perform(control,action){control.disabled=true;try{await action();notify('');await refresh()}catch(error){notify(error.message)}finally{control.disabled=false}}
function update(id,value,render){const signature=JSON.stringify(value);if(signatures.get(id)===signature)return;signatures.set(id,signature);render($(id))}
function date(value){return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function closeDialogs(){for(const dialog of document.querySelectorAll('dialog[open]'))dialog.close();browserRun=null;browserView=null;selectedGroup=null;groupMessageKey=null;$('browser-image').removeAttribute('src');$('browser-image').hidden=true;$('browser-input').value='';reviewRun=null;learnRun=null;routineKey=null;routineEdit=null;guideRun=null;guideKey=null;noteEdit=null}
function signOut(){authEpoch++;authenticated=false;selected=null;current=null;botsState=[];closeDialogs();signatures.clear();drafts.clear();routineRunKeys.clear();messageKey=null;eventItems=[];eventCursor=0;for(const form of document.querySelectorAll('form'))form.reset();for(const id of ['bots','group-list','feed','decisions','routines','notes','procedures','activity-list','deliveries','group-transcript','group-artifacts','group-recipients','group-create-members','history-results'])$(id).replaceChildren();$('bot-name').textContent='';$('responsibility').textContent='';$('app').hidden=true;$('login').hidden=false}
function selectBot(id){if(selected)drafts.set(selected,{message:$('message').value,key:messageKey});selected=id;current=null;closeDialogs();const draft=drafts.get(id);$('message').value=draft?.message||'';messageKey=draft?.key||null;signatures.clear();eventCursor=0;eventItems=[];for(const id of ['feed','decisions','routines','notes','procedures','activity-list','deliveries','history-results'])$(id).replaceChildren();$('history-search-form').reset();$('history-search-form').querySelector('.error').textContent=''}
function status(run){return run?run.status:'Ready'}
function showBots(bots){botsState=bots;update('bots',{bots,selected},container=>{container.replaceChildren();for(const bot of bots){const el=button('',async()=>{if(selected===bot.id)return;selectBot(bot.id);await refresh()},'bot'+(selected===bot.id?' selected':''));el.setAttribute('aria-current',selected===bot.id?'true':'false');el.append(node('strong',bot.name),node('span',bot.enabled?status(bot.latestRun):'Paused'));container.append(el)}if(!bots.length)container.append(node('p','No agents yet.','muted'))})}
function showRuns(runs,unreconciled,guidance,legacyTranscript){update('feed',{runs,unreconciled,guidance,legacyTranscript},container=>{const open=new Set([...container.querySelectorAll('details[open]')].map(el=>el.dataset.run));container.replaceChildren();if(!runs.length)container.append(node('p','Send the first task. Each task keeps its own conversation and progress.','empty'));for(const run of [...runs].reverse()){const el=node('article',undefined,'turn');const head=node('div',undefined,'row spread');head.append(node('span',(run.testMode?'Safe test · ':'')+run.status,'badge '+run.status),node('time',date(run.createdAt)));el.append(head,node('p',run.prompt,'prompt'));for(const message of guidance.filter(message=>message.runId===run.id)){el.append(node('p',message.content,'prompt'),node('p',message.sequence<=run.steeringCursor?'Guidance received by the agent':'Guidance saved — awaiting the agent','muted'))}if(run.output)el.append(node('div',run.output,'answer'));if(run.error)el.append(node('p',run.error,'error'));const actions=node('div',undefined,'actions');if(['running','waiting'].includes(run.status)&&run.acceptingMessages)actions.append(button('Guide task',async()=>{guideRun=run.id;guideKey=crypto.randomUUID();$('guide-dialog').showModal()}));if(['queued','running','waiting','blocked'].includes(run.status))actions.append(button('Stop task',()=>api('/api/runs/'+run.id+'/cancel',{}),'danger'));if(unreconciled.includes(run.id)){actions.append(button('Review effects',async()=>{reviewRun=run.id;$('reconcile-dialog').showModal()}))}else if(['failed','blocked'].includes(run.status)&&run.owner===null){actions.append(button('Retry task',()=>api('/api/runs/'+run.id+'/retry',{reconciled:run.status==='blocked'})))}if(run.status==='completed'&&run.owner===null&&run.browserStepCount>1)actions.append(button('Learn browser skill',async()=>{learnRun=run.id;$('learn-dialog').showModal()}));if(actions.childNodes.length)el.append(actions);const info=node('details');info.dataset.run=run.id;info.open=open.has(run.id);info.append(node('summary','Task conversation and details'),node('p','Occurrence: '+run.occurrenceId,'muted'));let loaded=false;info.addEventListener('toggle',async()=>{if(!info.open||loaded)return;loaded=true;try{const transcript=await api('/api/runs/'+run.id+'/transcript');if(info.isConnected)info.append(node('pre',JSON.stringify(transcript.messages,null,2)))}catch(error){loaded=false;if(info.isConnected)info.append(node('p',error.message,'error'))}});el.append(info);container.append(el)}if(legacyTranscript?.length){const legacy=node('details');legacy.append(node('summary','Unassigned legacy conversation'),node('p','Preserved from before task isolation. It is not used as context for any new task.','muted'),node('pre',JSON.stringify(legacyTranscript,null,2)));container.append(legacy)}})}
function showHistory(results){const container=$('history-results');container.replaceChildren();if(!results.length){container.append(node('p','No matching finished tasks in this agent history.','muted'));return}for(const result of results){const item=node('div',undefined,'routine');item.append(node('p',result.status+' · '+date(result.createdAt)+' · '+result.source,'muted'),node('p',result.promptExcerpt,'prompt'));if(result.resultExcerpt)item.append(node('p',result.resultExcerpt));const details=node('details');details.append(node('summary','Open full task transcript'));let loaded=false;details.addEventListener('toggle',async()=>{if(!details.open||loaded)return;loaded=true;try{const transcript=await api('/api/runs/'+encodeURIComponent(result.runId)+'/transcript');if(details.isConnected)details.append(node('pre',JSON.stringify(transcript.messages,null,2)))}catch(error){loaded=false;if(details.isConnected)details.append(node('p',error.message,'error'))}});item.append(details);container.append(item)}}
function showDecisions(decisions){update('decisions',decisions,container=>{container.replaceChildren();if(!decisions.length){container.append(node('p','All clear. Requests for approval appear here.','muted'));return}for(const decision of decisions){const el=node('div',undefined,'decision');el.append(node('h3',decision.kind==='question'?'A question for you':'Approve an action'));if(decision.kind==='permission'){el.append(node('p',decision.request.riskDescription||decision.request.message||'Review this action before it runs.','muted'),node('pre',JSON.stringify(decision.request,null,2)));const actions=node('div',undefined,'actions');for(const [label,answer] of [['Approve once','once'],['Decline','deny']])actions.append(button(label,()=>api('/api/decisions/'+decision.id,{fingerprint:decision.fingerprint,answer}),answer==='once'?'primary':'danger'));el.append(actions)}else if(decision.kind==='question'){const form=node('form');const questions=Array.isArray(decision.request.questions)?decision.request.questions:[];questions.forEach((q,i)=>{const label=node('label',q.question);const input=node('textarea');input.name=String(i);input.placeholder=q.placeholder||'';input.required=true;label.append(input);if(q.options)label.append(node('p',q.options.map(o=>o.label+(o.description?' — '+o.description:'')).join('\n'),'muted'));form.append(label)});const submit=node('button','Send answer','primary');submit.type='submit';form.append(submit);form.addEventListener('submit',event=>{event.preventDefault();perform(submit,()=>api('/api/decisions/'+decision.id,{fingerprint:decision.fingerprint,answer:Object.fromEntries(new FormData(form))}))});el.append(form,button('Skip question',()=>api('/api/decisions/'+decision.id,{fingerprint:decision.fingerprint,answer:null})))}else el.append(node('pre',JSON.stringify(decision.request,null,2)));container.append(el)}})}
function scheduleText(schedule){let text;if(schedule.kind==='daily')text='Daily at '+String(schedule.hour).padStart(2,'0')+':'+String(schedule.minute).padStart(2,'0')+' ('+schedule.timeZone+')';else if(schedule.kind==='interval')text='Every '+schedule.everyMs/60000+' minutes';else if(schedule.kind==='once')text=date(schedule.at);else text='On event: '+schedule.topic;return schedule.endsAt===undefined?text:text+' · through '+date(schedule.endsAt)}
function showRoutines(routines){update('routines',routines,container=>{container.replaceChildren();if(!routines.length)container.append(node('p','No routines scheduled.','muted'));for(const routine of routines){const el=node('div',undefined,'routine');el.append(node('strong',routine.name),node('p',scheduleText(routine.schedule),'muted'),node('p',routine.prompt));const actions=node('div',undefined,'actions');actions.append(button('Test safely',async()=>{const occurrenceId=crypto.randomUUID();await api('/api/bots/'+selected+'/routines/'+routine.id+'/test',{occurrenceId})}),button('Run once',async()=>{if(!window.confirm('Run this routine now? It may perform real actions and will still use the normal approval checks.'))return;let occurrenceId=routineRunKeys.get(routine.id);if(!occurrenceId){occurrenceId=crypto.randomUUID();routineRunKeys.set(routine.id,occurrenceId)}await api('/api/bots/'+selected+'/routines/'+routine.id+'/run',{occurrenceId});routineRunKeys.delete(routine.id)}),button('Edit routine',()=>openRoutine(routine)),button(routine.enabled?'Pause routine':'Enable routine',()=>api('/api/bots/'+selected+'/routines/'+routine.id,{enabled:!routine.enabled,version:routine.version})),button('Delete routine',async()=>{if(!window.confirm('Delete this schedule? Work already queued from it will continue as a separate task.'))return;await api('/api/bots/'+selected+'/routines/'+routine.id+'/delete',{version:routine.version});routineRunKeys.delete(routine.id)},'danger'));el.append(actions);const history=node('details');const summary=node('summary','Recent runs');history.append(summary);let loaded=false;history.addEventListener('toggle',async()=>{if(!history.open||loaded)return;loaded=true;try{const runs=await api('/api/bots/'+selected+'/routines/'+routine.id+'/runs');if(!history.isConnected)return;if(!runs.length)history.append(node('p','No runs recorded yet.','muted'));for(const run of runs){const item=node('div');item.append(node('p',(run.testMode?'Safe test · ':'')+run.status+' · '+date(run.createdAt),'muted'),node('p',run.prompt,'prompt'));if(run.output)item.append(node('p',run.output));if(run.error)item.append(node('p',run.error,'error'));history.append(item)}}catch(error){loaded=false;if(history.isConnected)history.append(node('p',error.message,'error'))}});el.append(history);container.append(el)}})}
function showProcedures(procedures){update('procedures',procedures,container=>{container.replaceChildren();if(!procedures.length)container.append(node('p','Learn a skill from a completed browser task.','muted'));for(const skill of procedures){const el=node('div',undefined,'routine');el.append(node('strong',skill.name),node('p',skill.status==='ready'?'Ready — every use rechecks the current page':'Needs a fresh demonstration','muted'),node('p','Observed '+date(skill.createdAt),'muted'));const link=node('a','Download SKILL.md');link.href='/api/bots/'+selected+'/procedures/'+skill.id;link.download='SKILL.md';el.append(link);container.append(el)}})}
function showNotes(notes){update('notes',notes,container=>{container.replaceChildren();if(!notes.length)container.append(node('p','The agent has no saved notes yet.','muted'));for(const note of notes){const el=node('div',undefined,'note');el.append(node('p',note.content),node('p','Source: '+note.source,'muted'),button('Edit note',()=>openNote(note)));container.append(el)}})}
function showDeliveries(targets,history){update('deliveries',{targets,history},container=>{container.replaceChildren();if(!targets.length){container.append(node('p','No outbound webhooks configured.','muted'));return}for(const target of targets){const el=node('div',undefined,'routine');el.append(node('strong',target.url),node('p',target.topics.join(', '),'muted'));const latest=history.find(item=>item.targetId===target.id);if(latest)el.append(node('p','Latest delivery: '+latest.status+' · attempt '+latest.attempt+(latest.responseStatus?' · HTTP '+latest.responseStatus:''),'muted'));const actions=node('div',undefined,'actions');actions.append(button(target.enabled?'Pause webhook':'Enable webhook',()=>api('/api/bots/'+selected+'/deliveries/'+target.id+'/enabled',{enabled:!target.enabled})));if(latest?.status==='failed')actions.append(button('Retry latest delivery',()=>api('/api/bots/'+selected+'/deliveries/'+latest.id+'/retry',{})));actions.append(button('Remove webhook',async()=>{if(!window.confirm('Remove this receiver and its pending delivery queue?'))return;await api('/api/bots/'+selected+'/deliveries/'+target.id+'/delete',{})},'danger'));el.append(actions);const key=node('details');key.append(node('summary','Receiver verification key'),node('p','Configure this public key at the receiver. Verify the signature over timestamp + "." + the exact request body. Reject old timestamps and deduplicate by delivery ID.','muted'),node('pre',target.publicKey));if(latest?.lastError)key.append(node('p',latest.lastError,'error'));el.append(key);container.append(el)}})}
function showGroups(groups){update('group-list',{groups,selectedGroup},container=>{container.replaceChildren();for(const group of groups){const el=button(group.name+' · '+group.members.length,async()=>selectGroup(group.id));el.className='bot'+(selectedGroup===group.id?' selected':'');container.append(el)}if(!groups.length)container.append(node('p','Create a room to coordinate agents.','muted'))})}
function populateGroupRecipients(group){const container=$('group-recipients');container.replaceChildren();for(const member of group.members){const label=node('label',member.name);const input=node('input');input.type='checkbox';input.name='recipients';input.value=member.botId;input.checked=member.enabled;input.disabled=!member.enabled;label.prepend(input);container.append(label)}}
async function selectGroup(id){selectedGroup=id;groupMessageKey=null;signatures.delete('group-transcript');signatures.delete('group-artifacts');$('group-message-form').reset();$('group-message-form').querySelector('.error').textContent='';$('group-dialog').showModal();await refreshGroup(id)}
async function refreshGroup(id){const epoch=authEpoch,data=await api('/api/groups/'+encodeURIComponent(id));if(selectedGroup!==id||epoch!==authEpoch)return;const group=data.group;$('group-title').textContent=group.name;$('group-description').textContent='Members: '+group.members.map(member=>member.name).join(', ')+(group.shareBrowser?' · shared Codimium browser, queued one task at a time':' · private browser profiles');populateGroupRecipientsIfNeeded(group);const memberNames=new Map(group.members.map(member=>[member.botId,member.name]));update('group-transcript',{messages:data.messages,runs:data.runs},container=>{container.replaceChildren();if(!data.messages.length)container.append(node('p','No messages yet.','muted'));for(const message of data.messages){const entry=node('div',undefined,'group-message'),sender=message.sender==='user'?'You':memberNames.get(message.botId)||'Former member';entry.append(node('strong',sender+' · '+date(message.createdAt)),node('p',message.content));if(message.sender==='user'){const runs=data.runs.filter(run=>run.groupMessageId===message.id);if(runs.length){const statuses=node('div',undefined,'group-members');for(const run of runs){const member=group.members.find(item=>item.botId===run.botId);statuses.append(node('span',(member?.name||'Agent')+': '+run.status,'muted'));if(['blocked','failed'].includes(run.status))statuses.append(button('Review '+(member?.name||'agent'),async()=>{selectBot(run.botId);await refresh()}))}entry.append(statuses)}}container.append(entry)}});update('group-artifacts',data.artifacts,container=>{container.replaceChildren();if(!data.artifacts.length)container.append(node('p','Agents can publish versioned shared artifacts with bot_control.','muted'));for(const artifact of data.artifacts){const details=node('details'),summary=node('summary',artifact.name+' · v'+artifact.version);details.append(summary,node('p','Updated '+date(artifact.updatedAt),'muted'));let loaded=false;details.addEventListener('toggle',async()=>{if(!details.open||loaded)return;loaded=true;try{const value=await api('/api/groups/'+encodeURIComponent(id)+'/artifacts/'+encodeURIComponent(artifact.name));if(details.isConnected)details.append(node('pre',value.content))}catch(error){loaded=false;if(details.isConnected)details.append(node('p',error.message,'error'))}});container.append(details)}})}
function populateGroupRecipientsIfNeeded(group){const form=$('group-message-form');if(form.dataset.groupId===group.id)return;form.dataset.groupId=group.id;populateGroupRecipients(group)}
async function refreshGroups(epoch){const data=await api('/api/groups');if(epoch!==authEpoch)return;showGroups(data.groups);if(!selectedGroup)return;if(!data.groups.some(group=>group.id===selectedGroup)){$('group-dialog').close();selectedGroup=null;signatures.delete('group-transcript');signatures.delete('group-artifacts');return}await refreshGroup(selectedGroup)}
function openNote(note){noteEdit=note||null;const form=$('note-form');form.reset();form.querySelector('.error').textContent='';form.elements.content.value=note?.content||'';form.elements.source.value=note?.source||'user:panel';form.elements.expiresAt.value=note?.expiresAt===null||!note?'':new Date(note.expiresAt-new Date(note.expiresAt).getTimezoneOffset()*60000).toISOString().slice(0,-1);$('remove-note').hidden=!note;$('note-dialog').showModal()}
async function refresh(){if(refreshing)return;refreshing=true;const epoch=authEpoch;try{const state=await api('/api/bots');if(epoch!==authEpoch)return;authenticated=true;$('login').hidden=true;$('app').hidden=false;$('connection').textContent='Supervisor connected';if(!state.bots.some(b=>b.id===selected))selectBot(state.bots[0]?.id||null);showBots(state.bots);await refreshGroups(epoch);$('composer').hidden=!selected;$('toggle-bot').hidden=!selected;$('new-routine').hidden=!selected;$('export-bot').hidden=!selected;$('delete-bot').hidden=!selected;$('new-delivery').hidden=!selected;$('history-section').hidden=!selected;browserOpen.hidden=!selected;if(!selected)return;const id=selected;const data=await api('/api/bots/'+id);if(id!==selected||epoch!==authEpoch)return;current=data;$('bot-name').textContent=data.bot.name;$('responsibility').textContent=data.bot.instructions;$('toggle-bot').textContent=data.bot.enabled?'Pause new work':'Enable agent';showRuns(data.runs,data.unreconciledRuns,data.guidance,data.legacyTranscript);showDecisions(data.decisions);showRoutines(data.routines);showNotes(data.notes);showProcedures(data.procedures);const deliveryData=await api('/api/bots/'+id+'/deliveries');if(id!==selected||epoch!==authEpoch)return;showDeliveries(deliveryData.targets,deliveryData.history);const events=await api('/api/bots/'+id+'/events?after='+eventCursor);if(id!==selected||epoch!==authEpoch)return;if(events.length){eventCursor=events.at(-1).event_seq;eventItems.push(...events);eventItems=eventItems.slice(-80);const container=$('activity-list');container.replaceChildren();for(const event of eventItems){const el=node('div');el.append(node('strong',event.type),node('p',date(event.created_at),'muted'));const details=node('details');details.append(node('summary','Details'),node('pre',JSON.stringify(event.payload,null,2)));el.append(details);container.append(el)}}}catch(error){if(authenticated){$('connection').textContent='Connection interrupted';notify(error.message+' Your queued tasks remain saved.')}}finally{refreshing=false}}
$('history-search-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,control=submitter(event),query=String(new FormData(form).get('query')||'').trim(),botId=selected,epoch=authEpoch;control.disabled=true;form.querySelector('.error').textContent='';try{if(!botId)throw new Error('Select an agent first');const results=await api('/api/bots/'+encodeURIComponent(botId)+'/history?query='+encodeURIComponent(query));if(botId===selected&&epoch===authEpoch)showHistory(results)}catch(error){form.querySelector('.error').textContent=error.message}finally{control.disabled=false}});
$('login-form').addEventListener('submit',async event=>{event.preventDefault();const submit=submitter(event);submit.disabled=true;try{await api('/api/login',{token:$('token').value});$('token').value='';$('login-error').textContent='';await refresh()}catch(error){$('login-error').textContent=error.message}finally{submit.disabled=false}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout',{});signOut();notify('')}catch(error){notify(error.message)}});
$('group-dialog').addEventListener('close',()=>{selectedGroup=null;groupMessageKey=null;signatures.delete('group-transcript');signatures.delete('group-artifacts')});
$('new-group').addEventListener('click',()=>{const form=$('group-create-form'),container=$('group-create-members');form.reset();form.querySelector('.error').textContent='';container.replaceChildren();for(const bot of botsState.filter(item=>item.enabled)){const label=node('label',bot.name);const input=node('input');input.type='checkbox';input.name='botIds';input.value=bot.id;label.prepend(input);container.append(label)}if(container.childElementCount<2)container.append(node('p','Enable at least two agents before creating a group.','muted'));$('group-create-dialog').showModal()});
$('group-create-form').addEventListener('submit',event=>submitForm(event,async fields=>{const group=await api('/api/groups',{name:fields.get('name'),botIds:fields.getAll('botIds'),shareBrowser:fields.get('shareBrowser')==='on'});selectedGroup=group.id;await refreshGroup(group.id)}));
$('group-message-form').addEventListener('input',()=>{groupMessageKey=null});
$('group-message-form').addEventListener('submit',event=>submitForm(event,async fields=>{if(!selectedGroup)throw new Error('Select a collaboration group first');groupMessageKey??=crypto.randomUUID();await api('/api/groups/'+encodeURIComponent(selectedGroup)+'/messages',{message:fields.get('message'),messageId:groupMessageKey,recipients:fields.getAll('recipients')});groupMessageKey=null}));
$('delete-group').addEventListener('click',event=>perform(event.currentTarget,async()=>{if(!selectedGroup)return;const group=await api('/api/groups/'+encodeURIComponent(selectedGroup));const typed=window.prompt('This permanently deletes '+group.group.name+' including its shared messages, artifacts and group browser profile. Type the exact group name to continue.');if(typed!==group.group.name)return;await api('/api/groups/'+encodeURIComponent(selectedGroup)+'/delete',{confirmation:typed});$('group-dialog').close()}));
$('new-bot').addEventListener('click',()=>{$('create-dialog').showModal()});
for(const control of document.querySelectorAll('[data-close]'))control.addEventListener('click',()=>control.closest('dialog').close());
async function submitForm(event,action){event.preventDefault();const form=event.currentTarget,control=submitter(event);control.disabled=true;try{await action(new FormData(form));form.closest('dialog')?.close();form.reset();form.querySelector('.error').textContent='';await refresh()}catch(error){form.querySelector('.error').textContent=error.message}finally{control.disabled=false}}
const reviewerCreateLabel=node('label','Completion reviewer model (optional)');const reviewerCreateInput=document.createElement('input');reviewerCreateInput.name='reviewerModel';reviewerCreateInput.maxLength=128;reviewerCreateInput.pattern='[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}';reviewerCreateInput.placeholder='Use the pod model';reviewerCreateLabel.append(reviewerCreateInput,node('span','The completion check always runs. Leave blank to use this pod’s main model.','muted'));$('create-form').elements.agentConfig.closest('label').after(reviewerCreateLabel);
$('create-form').addEventListener('submit',event=>submitForm(event,async fields=>{const input=Object.fromEntries(fields);if(!input.agentConfig)delete input.agentConfig;if(!input.reviewerModel)delete input.reviewerModel;const bot=await api('/api/bots',input);selectBot(bot.id)}));
$('composer').addEventListener('submit',event=>{event.preventDefault();const id=selected,message=$('message').value,control=submitter(event);messageKey??=crypto.randomUUID();const occurrenceId=messageKey;perform(control,async()=>{await api('/api/bots/'+id+'/messages',{message,occurrenceId});if(selected===id){if($('message').value===message)$('message').value='';messageKey=null}else if(drafts.get(id)?.message===message)drafts.delete(id)})});
$('message').addEventListener('input',()=>{messageKey=null});
$('toggle-bot').addEventListener('click',event=>perform(event.currentTarget,()=>api('/api/bots/'+selected+'/enabled',{enabled:!current.bot.enabled})));
$('export-bot').addEventListener('click',()=>{if(!selected)return;const link=document.createElement('a');link.href='/api/bots/'+encodeURIComponent(selected)+'/export';link.download='deepseek-bot-'+selected+'.json';link.click()});
$('delete-bot').addEventListener('click',async event=>{if(!current)return;const bot=current.bot,typed=window.prompt('This permanently deletes '+bot.name+' and its saved history, agent state and Codimium profile. Project files are kept. Type the exact agent name to continue.');if(typed!==bot.name)return;await perform(event.currentTarget,async()=>{await api('/api/bots/'+encodeURIComponent(bot.id)+'/delete',{confirmation:typed});drafts.delete(bot.id);selected=null;current=null;signatures.clear()})});
function scheduleFields(){const kind=$('routine-form').elements.kind.value;for(const section of document.querySelectorAll('[data-schedule]')){section.hidden=section.dataset.schedule==='recurring'?kind==='once':section.dataset.schedule!==kind;for(const input of section.querySelectorAll('input'))input.required=!section.hidden&&input.name!=='endsAt'}}
function procedureFields(){const skill=current?.procedures.find(p=>p.id===$('routine-form').elements.procedureId.value),container=$('procedure-inputs');container.replaceChildren();if(!skill)return;for(const step of skill.steps){if(!step.input)continue;const label=node('label',step.input+(step.name?' — '+step.name:''));const input=node('input');input.name='procedure:'+step.input;input.required=true;input.maxLength=10000;label.append(input);container.append(label)}container.append(node('p','Use non-sensitive values for this routine. Passwords and login codes require human takeover.','muted'))}
function localDateTime(value){const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,-1)}
function openRoutine(routine=null){routineEdit=routine;routineKey=routine?null:crypto.randomUUID();const form=$('routine-form'),fields=form.elements;form.reset();form.querySelector('.error').textContent='';$('routine-title').textContent=routine?'Edit routine':'Add routine';$('routine-submit').textContent=routine?'Save changes':'Add routine';fields.name.value=routine?.name||'';fields.prompt.value=routine?.prompt||'';const select=fields.procedureId;select.replaceChildren(new Option('No browser skill',''));for(const skill of current?.procedures||[]){if(skill.status==='ready')select.append(new Option(skill.name,skill.id));else if(skill.id===routine?.procedureId)select.append(new Option(skill.name+' — needs review',skill.id))}select.value=routine?.procedureId&&current?.procedures.some(p=>p.id===routine.procedureId&&p.status==='ready')?routine.procedureId:'';const schedule=routine?.schedule;fields.kind.value=schedule?.kind||'daily';fields.timeZone.value=schedule?.kind==='daily'?schedule.timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone;if(schedule?.kind==='daily')fields.time.value=String(schedule.hour).padStart(2,'0')+':'+String(schedule.minute).padStart(2,'0');if(schedule?.kind==='interval')fields.minutes.value=String(schedule.everyMs/60000);if(schedule?.kind==='once')fields.at.value=localDateTime(schedule.at);if(schedule?.kind==='event')fields.topic.value=schedule.topic;if(schedule?.endsAt!==undefined)fields.endsAt.value=localDateTime(schedule.endsAt);procedureFields();if(schedule&&routine?.procedureId&&select.value===routine.procedureId)for(const [key,value] of Object.entries(routine.procedureInputs||{})){const input=form.elements.namedItem('procedure:'+key);if(input)input.value=value}scheduleFields();$('routine-dialog').showModal()}
$('new-note').addEventListener('click',()=>openNote(null));
$('note-form').addEventListener('submit',event=>submitForm(event,fields=>api('/api/bots/'+selected+'/notes'+(noteEdit?'/'+noteEdit.id:''),{content:fields.get('content'),source:fields.get('source'),expiresAt:fields.get('expiresAt')?new Date(fields.get('expiresAt')).getTime():null,...(noteEdit?{version:noteEdit.version}:{})})));
$('remove-note').addEventListener('click',event=>perform(event.currentTarget,async()=>{if(!noteEdit)return;await api('/api/bots/'+selected+'/notes/'+noteEdit.id+'/remove',{version:noteEdit.version});$('note-dialog').close();$('note-form').reset();noteEdit=null}));
$('guide-form').addEventListener('input',()=>{guideKey=crypto.randomUUID()});
$('guide-form').addEventListener('submit',event=>submitForm(event,fields=>api('/api/runs/'+guideRun+'/messages',{message:fields.get('message'),messageId:guideKey})));
$('learn-form').addEventListener('submit',event=>submitForm(event,async fields=>{await api('/api/bots/'+selected+'/procedures',{runId:learnRun,name:fields.get('name')})}));
$('routine-form').elements.procedureId.addEventListener('change',procedureFields);
$('new-routine').addEventListener('click',()=>openRoutine());$('new-delivery').addEventListener('click',()=>{$('delivery-form').reset();$('delivery-form').querySelector('.error').textContent='';$('delivery-dialog').showModal()});$('delivery-form').addEventListener('submit',event=>submitForm(event,async fields=>{const topics=fields.getAll('topics');if(!topics.length)throw new Error('Choose at least one task outcome');const target=await api('/api/bots/'+selected+'/deliveries',{url:fields.get('url'),topics});notify('Webhook added. Share its public verification key with the receiver.');return target}));
$('routine-form').elements.kind.addEventListener('change',scheduleFields);
$('routine-form').addEventListener('input',()=>{if(!routineEdit)routineKey=crypto.randomUUID()});
$('routine-form').addEventListener('submit',event=>submitForm(event,async fields=>{const kind=fields.get('kind');let schedule;if(kind==='daily'){const [hour,minute]=fields.get('time').split(':').map(Number);schedule={kind,hour,minute,timeZone:fields.get('timeZone')}}else if(kind==='interval')schedule={kind,everyMs:Number(fields.get('minutes'))*60000};else if(kind==='once')schedule={kind,at:new Date(fields.get('at')).getTime()};else schedule={kind,topic:fields.get('topic')};if(kind!=='once'&&fields.get('endsAt'))schedule.endsAt=new Date(fields.get('endsAt')).getTime();const procedureId=fields.get('procedureId'),payload={name:fields.get('name'),prompt:fields.get('prompt'),schedule,...(procedureId?{procedureId,procedureInputs:Object.fromEntries([...fields].filter(([key])=>key.startsWith('procedure:')).map(([key,value])=>[key.slice(10),value]))}:{})};if(routineEdit){await api('/api/bots/'+selected+'/routines/'+routineEdit.id,{...payload,procedureId:procedureId||null,version:routineEdit.version});routineEdit=null}else{await api('/api/bots/'+selected+'/routines',{...payload,occurrenceId:routineKey});routineKey=null}}));
$('reconcile-form').addEventListener('submit',event=>submitForm(event,fields=>api('/api/runs/'+reviewRun+'/reconcile',{evidence:fields.get('evidence')})));
const browserOpen=button('Open Codimium',async()=>{await browserStatus();$('browser-dialog').showModal()});browserOpen.hidden=true;$('responsibility').after(browserOpen);
const retentionLabel=node('label','Automatically remove completed run history after');const retentionSelect=node('select');retentionSelect.id='retention-days';for(const [value,label] of [['never','Keep indefinitely'],['30','30 days'],['90','90 days'],['180','180 days'],['365','1 year'],['730','2 years']])retentionSelect.append(new Option(label,value));retentionLabel.append(retentionSelect);const retentionHelp=node('p','Runs with uncertain effects or used to create browser skills are kept for review.');retentionHelp.className='muted';$('export-bot').closest('section').insertBefore(retentionLabel,$('export-bot').closest('.actions'));$('export-bot').closest('section').insertBefore(retentionHelp,$('export-bot').closest('.actions'));const previousRefresh=refresh;refresh=async()=>{await previousRefresh();if(current){const days=current.bot.retentionDays===null?'never':String(current.bot.retentionDays);if(!Array.from(retentionSelect.options).some(option=>option.value===days))retentionSelect.add(new Option(days+' days',days));retentionSelect.value=days}};retentionSelect.addEventListener('change',event=>perform(retentionSelect,async()=>{const days=retentionSelect.value==='never'?null:Number(retentionSelect.value);await api('/api/bots/'+selected+'/retention',{days})}));
async function browserStatus(){const state=await api('/api/bots/'+selected+'/browser');browserRun=state.runId;$('browser-state').textContent=!state.runId?'This agent has no active task.':state.held?'You have control. Return it when you finish.':'The agent has control.';$('browser-take').disabled=!state.runId;$('browser-release').disabled=!state.runId||!state.held;const tabSelect=$('browser-tab');tabSelect.replaceChildren();const main=state.contexts.find(context=>context.key.endsWith('|main'));if(main){main.tabs.forEach((tab,index)=>{const option=node('option',index+': '+(tab.title||tab.url));option.value=index;tabSelect.append(option)});tabSelect.value=main.active}return state}
let reviewerDirtyFor = null;const reviewerSection=node('section'),reviewerTitle=node('h2','Completion review'),reviewerInfo=node('p','The completion check is mandatory. Choose a model supported by this pod’s provider, or leave blank to inherit its active model. If review cannot run, the goal stays active.','muted'),reviewerForm=document.createElement('form'),reviewerModelLabel=node('label','Reviewer model'),reviewerModelInput=document.createElement('input'),reviewerHelp=node('p','Leave blank to use the pod model. Changes apply to new runs; active runs keep their starting setting.','muted'),reviewerError=node('p'),reviewerSave=document.createElement('button');reviewerSection.append(reviewerTitle,reviewerInfo);reviewerForm.id='reviewer-model-form';reviewerModelInput.id='reviewer-model';reviewerModelInput.name='model';reviewerModelInput.maxLength=128;reviewerModelInput.pattern='[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}';reviewerModelInput.placeholder='Use pod model';reviewerModelLabel.append(reviewerModelInput);reviewerError.className='error';reviewerError.setAttribute('role','alert');reviewerSave.type='submit';reviewerSave.className='primary';reviewerSave.textContent='Save reviewer model';reviewerForm.append(reviewerModelLabel,reviewerHelp,reviewerSave,reviewerError);reviewerSection.append(reviewerForm);reviewerSection.hidden=true;$('history-section').before(reviewerSection);reviewerModelInput.addEventListener('input',()=>{reviewerDirtyFor=selected});reviewerForm.addEventListener('submit',event=>{event.preventDefault();const control=submitter(event),podId=selected;control.disabled=true;reviewerError.textContent='';void api('/api/bots/'+encodeURIComponent(podId)+'/reviewer-model',{model:reviewerModelInput.value.trim()||null}).then(()=>{if(reviewerDirtyFor===podId)reviewerDirtyFor=null;notify('Completion reviewer saved.');return refresh()}).catch(error=>{reviewerError.textContent=error.message}).finally(()=>{control.disabled=false})});const refreshWithReviewer=refresh;refresh=async()=>{await refreshWithReviewer();reviewerSection.hidden=!selected;if(current&&reviewerDirtyFor!==selected&&document.activeElement!==reviewerModelInput){reviewerModelInput.value=current.bot.reviewerModel||'';reviewerDirtyFor=null}};
async function browserCommand(command,args){if(!browserRun)throw new Error('This agent has no active browser task');return api('/api/bots/'+selected+'/browser',{runId:browserRun,command,args})}
async function browserImage(){const result=await browserCommand('image');browserView=result;$('browser-image').src='data:image/jpeg;base64,'+result.image;$('browser-image').hidden=false}
async function browserAction(command,args){await browserCommand(command,args);await browserStatus();await browserImage()}
$('browser-take').addEventListener('click',event=>perform(event.currentTarget,()=>browserAction('take')));
$('browser-release').addEventListener('click',event=>perform(event.currentTarget,async()=>{await browserCommand('release');browserView=null;$('browser-image').hidden=true;$('browser-input').value='';await browserStatus()}));
$('browser-refresh').addEventListener('click',event=>perform(event.currentTarget,async()=>{await browserStatus();await browserImage()}));
$('browser-navigation').addEventListener('submit',event=>{event.preventDefault();perform(submitter(event),()=>browserAction('navigate',{url:$('browser-url').value}))});
$('browser-text').addEventListener('submit',event=>{event.preventDefault();const text=$('browser-input').value;$('browser-input').value='';perform(submitter(event),()=>browserAction('type',{text}))});
$('browser-press').addEventListener('click',event=>perform(event.currentTarget,()=>browserAction('press',{key:$('browser-key').value})));
$('browser-up').addEventListener('click',event=>perform(event.currentTarget,()=>browserAction('scroll',{delta:-550})));
$('browser-down').addEventListener('click',event=>perform(event.currentTarget,()=>browserAction('scroll',{delta:550})));
$('browser-accept').addEventListener('click',event=>perform(event.currentTarget,async()=>{const state=await browserStatus();const text=state.dialog?.type==='prompt'?$('browser-input').value:undefined;$('browser-input').value='';await browserAction('dialog',{accept:true,text})}));
$('browser-dismiss').addEventListener('click',event=>perform(event.currentTarget,()=>browserAction('dialog',{accept:false})));
$('browser-tab').addEventListener('change',event=>perform(event.currentTarget,()=>browserAction('tab',{index:Number(event.currentTarget.value)})));
$('browser-image').addEventListener('click',event=>{if(!browserView)return;const bounds=event.currentTarget.getBoundingClientRect();perform(event.currentTarget,()=>browserAction('click',{viewId:browserView.id,x:(event.clientX-bounds.left)*browserView.width/bounds.width,y:(event.clientY-bounds.top)*browserView.height/bounds.height}))});
$('browser-image').addEventListener('keydown',event=>{if(!['Enter','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Backspace','Escape'].includes(event.key))return;if(event.key==='Tab')return;event.preventDefault();perform(event.currentTarget,()=>browserAction('press',{key:event.key}))});
$('browser-dialog').addEventListener('close',()=>{browserView=null;browserRun=null;$('browser-image').removeAttribute('src');$('browser-image').hidden=true;$('browser-input').value=''});
setInterval(()=>{if(authenticated&&!document.hidden)void refresh()},2000);document.addEventListener('visibilitychange',()=>{if(authenticated&&!document.hidden)void refresh()});void refresh();
</script></body></html>`
