// Installed CLI smoke: bun tests/bot-packaged-check.ts /absolute/path/to/deepseek
import assert from 'node:assert/strict'
import { Database } from 'bun:sqlite'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { BotStore } from '../src/bots/store.js'
import { scrubbedEnv } from '../src/utils/platform.js'

const executable = process.argv[2]
assert.ok(executable, 'Provide the installed executable')
const directory = await mkdtemp(join(tmpdir(), 'deepseek-packaged-bot-')), path = join(directory, 'state.db')
const command = (...args: string[]) => Bun.spawnSync([executable, 'pods', ...args, '--db', path], { env: scrubbedEnv(), stdout: 'pipe', stderr: 'pipe' })
const json = (...args: string[]) => {
  const result = command(...args)
  assert.equal(result.exitCode, 0, result.stderr.toString())
  return JSON.parse(result.stdout.toString())
}
let store: BotStore | undefined
try {
  const help = command('help')
  assert.equal(help.exitCode, 0, help.stderr.toString())
  assert.match(help.stdout.toString(), /deepseek pods group create/)
  assert.match(help.stdout.toString(), /deepseek pods history/)
  assert.match(help.stdout.toString(), /pods steer RUN MESSAGE/)
  assert.match(help.stdout.toString(), /pods test-routine POD ROUTINE/)
  assert.equal(help.stdout.toString().includes('deepseek bots'), false)
  const bot = json('create', 'packaged', '--project', directory, '--instructions', 'Follow the current task and user guidance.')
  assert.equal(bot.reviewerModel, undefined)
  assert.deepEqual(json('reviewer-model', bot.id), { reviewerModel: null })
  assert.equal(json('reviewer-model', bot.id, '--model', 'quality/reviewer-v2').reviewerModel, 'quality/reviewer-v2')
  assert.equal(json('reviewer-model', bot.id, '--model', 'inherit').reviewerModel, undefined)
  assert.deepEqual(json('retention', bot.id), { retentionDays: null })
  assert.equal(json('retention', bot.id, '--days', '90').retentionDays, 90)
  assert.equal(json('retention', bot.id, '--days', 'never').retentionDays, null)
  const endsAt = Date.now() + 3_600_000
  const expiringRoutine = json('routine', bot.id, '--name', 'Temporary installed routine', '--prompt', 'Check current sources', '--schedule', JSON.stringify({ kind: 'interval', everyMs: 60_000, endsAt }))
  assert.equal(expiringRoutine.schedule.endsAt, endsAt)
  assert.equal(json('routines', bot.id).find((routine: { id: string }) => routine.id === expiringRoutine.id).schedule.endsAt, endsAt)
  // Inspect the shipped schema before a source Store can migrate anything.
  const database = new Database(path, { readonly: true })
  try {
    assert.equal(database.query<{ version: number }, []>('SELECT max(version) AS version FROM _schema_version').get()!.version, 29)
    const tables = database.query<{ name: string }, []>("SELECT name FROM sqlite_master WHERE type='table'").all().map(row => row.name)
    assert.ok(tables.includes('bot_event_receipts'))
    assert.ok(tables.includes('bot_webhook_credentials'))
    assert.ok(tables.includes('bot_webhook_rate_limits'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_webhook_credentials)').all().some(column => column.name === 'signature_public_key'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_runs)').all().some(column => column.name === 'transcript'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_runs)').all().some(column => column.name === 'test_mode'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_runs)').all().some(column => column.name === 'retention_pending'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_runs)').all().some(column => column.name === 'parent_run_id'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_runs)').all().some(column => column.name === 'handoff_message_id'))
    assert.ok(tables.includes('bot_delivery_targets'))
    assert.ok(tables.includes('bot_delivery_outbox'))
    assert.ok(tables.includes('bot_groups'))
    assert.ok(tables.includes('bot_group_members'))
    assert.ok(tables.includes('bot_group_messages'))
    assert.ok(tables.includes('bot_group_artifacts'))
    assert.ok(tables.includes('bot_run_search'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_runs)').all().some(column => column.name === 'group_id'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_instances)').all().some(column => column.name === 'deleting'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_instances)').all().some(column => column.name === 'retention_days'))
    assert.ok(database.query<{ name: string }, []>('PRAGMA table_info(bot_instances)').all().some(column => column.name === 'reviewer_model'))
  }
  finally { database.close() }
  const note = json('remember', bot.id, 'Installed saved fact', '--source', 'user:fixture')
  assert.equal(note.version, 1)
  const corrected = json('update-note', bot.id, note.id, 'Installed corrected fact', '--source', 'user:fixture', '--version', '1')
  assert.equal(corrected.id, note.id); assert.equal(corrected.version, 2)
  assert.deepEqual(json('update-note', bot.id, note.id, corrected.content, '--source', corrected.source, '--version', '1'), corrected)
  assert.notEqual(command('update-note', bot.id, note.id, 'Stale edit', '--source', 'fixture', '--version', '1').exitCode, 0)
  assert.deepEqual(json('notes', bot.id), [corrected])
  assert.notEqual(command('forget', bot.id, note.id, '--version', '1').exitCode, 0)
  assert.deepEqual(json('forget', bot.id, note.id, '--version', '2'), { removed: true })
  assert.deepEqual(json('notes', bot.id), [])
  const queued = json('send', bot.id, 'Original installed task', '--occurrence', 'packaged-occurrence')
  store = new BotStore({ path })
  assert.equal(store.claim(bot.id, 'packaged-fixture')!.id, queued.id)
  const message = json('steer', queued.id, 'Use the revised source for the same task.', '--occurrence', 'packaged-guidance')
  assert.deepEqual(json('steer', queued.id, message.content, '--occurrence', message.id), message)
  const conversation = json('show', bot.id)
  assert.equal(conversation.runs.length, 1)
  assert.equal(conversation.runs[0].occurrenceId, 'packaged-occurrence')
  assert.deepEqual(conversation.guidance, [message])
  assert.equal(store.events(bot.id).query({ type: 'BotRunSteered' }).length, 1)
  store.checkpoint(queued.id, 'packaged-fixture', [{ role: 'user', content: message.content }], undefined, undefined, message.sequence)
  assert.equal(store.sealRun(queued.id, 'packaged-fixture'), true)
  store.finish(queued.id, 'packaged-fixture', 'completed', 'Installed command evidence'); store.acknowledgeStop(queued.id, 'packaged-fixture')
  const stopped = command('steer', queued.id, 'Too late', '--occurrence', 'late-guidance')
  assert.notEqual(stopped.exitCode, 0)
  assert.equal(store.steeringMessages(queued.id).length, 1)
  assert.ok(json('history', bot.id, 'Installed command evidence').some((run: { runId: string }) => run.runId === queued.id))
  const researcher = json('create', 'packaged-researcher', '--project', directory, '--instructions', 'Compare the observed results.', '--reviewer-model', 'quality/reviewer-v1')
  assert.equal(researcher.reviewerModel, 'quality/reviewer-v1')
  const group = json('group', 'create', 'Packaged room', '--members', bot.id + ',' + researcher.id)
  assert.equal(group.name, 'Packaged room')
  const groupWork = json('group', 'send', group.id, 'Compare this packaged task.', '--occurrence', 'packaged-group-task')
  assert.equal(groupWork.runs.length, 2)
  assert.equal(json('group', 'show', group.id).group.id, group.id)
  for (const run of groupWork.runs as Array<{ id: string }>) assert.equal(command('cancel', run.id).exitCode, 0)
  assert.deepEqual(json('group', 'delete', group.id, '--confirm', group.name), { deleted: true })
  const oldCommand = Bun.spawnSync([executable, 'bots', 'help'], { env: scrubbedEnv(), stdout: 'pipe', stderr: 'pipe' })
  assert.notEqual(oldCommand.exitCode, 0)
  assert.match(oldCommand.stderr.toString(), /deepseek pods/)
  const manual = json('run-routine', bot.id, expiringRoutine.id, '--occurrence', 'packaged-manual-run')
  assert.equal(manual.source, `routine-manual:${expiringRoutine.id}:v${expiringRoutine.version}`)
  assert.equal(json('routine-runs', bot.id, expiringRoutine.id).some((run: { id: string }) => run.id === manual.id), true)
  const safeTest = json('test-routine', bot.id, expiringRoutine.id, '--occurrence', 'packaged-safe-test')
  assert.equal(safeTest.testMode, true)
  assert.equal(safeTest.source, `routine-test:${expiringRoutine.id}:v${expiringRoutine.version}`)
  assert.equal(json('routine-runs', bot.id, expiringRoutine.id).some((run: { id: string; testMode: boolean }) => run.id === safeTest.id && run.testMode), true)
  assert.deepEqual(json('delete-routine', bot.id, expiringRoutine.id, '--version', String(expiringRoutine.version)), { deleted: true })
  assert.deepEqual(json('routine-runs', bot.id, expiringRoutine.id).map((run: { id: string }) => run.id), [safeTest.id, manual.id])
  assert.equal(json('show', bot.id).runs.some((run: { id: string; testMode: boolean }) => run.id === safeTest.id && run.testMode), true)
  const backup = json('export', bot.id)
  assert.equal(backup.schemaVersion, 1)
  assert.equal(backup.bot.id, bot.id)
  if (store) { store.close(); store = undefined }
  assert.deepEqual(json('delete', bot.id, '--confirm', bot.name), { deleted: true, filesRemoved: true })
  assert.deepEqual(json('delete', researcher.id, '--confirm', researcher.name), { deleted: true, filesRemoved: true })
  assert.deepEqual(json('list'), [])
  console.log('Installed DeepSeek Pods check passed: schema 29 bounded history search and configurable completion reviewer, group collaboration, retention, handoff routing and signed delivery, safe routine tests, data lifecycle, JSON export and confirmed deletion, routine expiry, run transcripts, webhook/rate-limit migrations, note and guidance controls, idempotency and terminal fencing.')
} finally { store?.close(); await rm(directory, { recursive: true, force: true }) }
