// Runnable real-HTTP check: bun tests/bot-web-check.ts
import assert from 'node:assert/strict'
import { createPrivateKey, sign } from 'node:crypto'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { setTimeout as delay } from 'node:timers/promises'
import { BotStore } from '../src/bots/store.js'
import { startBotWebServer } from '../src/bots/web.js'
import { BrowserService, contextKey } from '../src/browser/service.js'
import { findChromium } from '../src/utils/platform.js'
import { BOT_PANEL_HTML } from '../src/bots/panel.js'

const directory = await mkdtemp(join(tmpdir(), 'deepseek-bot-web-'))
const store = new BotStore({ path: join(directory, 'state.db') })
const token = 'panel-check-only-' + 'x'.repeat(48)
// TypeScript cannot parse JavaScript inside an HTML string.
new Function(BOT_PANEL_HTML.match(/<script nonce="__NONCE__">([\s\S]*?)<\/script>/)![1]!)
assert.throws(() => startBotWebServer(store, { token: 'short' }), /32 characters/)
assert.throws(() => startBotWebServer(store, { token, hostname: '0.0.0.0' }), /HTTPS/)
assert.throws(() => startBotWebServer(store, { token, publicUrl: 'http://example.com' }), /HTTPS/)
const { server, url } = startBotWebServer(store, { token, port: 0 })
const request = (path: string, data?: unknown, headers: Record<string, string> = {}) => fetch(url + path, {
  method: data === undefined ? 'GET' : 'POST',
  headers: { ...(data === undefined ? {} : { 'content-type': 'application/json', origin: url }), ...headers },
  body: data === undefined ? undefined : JSON.stringify(data),
})
let cookie = ''
const authorized = async (path: string, data?: unknown) => {
  const response = await request(path, data, { cookie })
  const value = await response.json() as any
  assert.equal(response.ok, true, JSON.stringify(value))
  return value
}
try {
  if (process.argv.includes('--serve-fixture')) {
    const bot = store.createBot({ name: 'engineer', projectRoot: directory, instructions: 'Maintain DeepSeek Code and report observed results for review.' })
    store.createBot({ name: 'researcher', projectRoot: directory, instructions: 'Check current sources and save findings with their provenance.' })
    const job = store.enqueue(bot.id, 'Inspect the browser session persistence and prepare the change.')
    store.claim(bot.id, 'web-fixture')
    store.requestDecision(job.id, 'web-fixture', 'permission', { toolName: 'shell', args: { command: 'bun run typecheck' }, riskDescription: 'Run the project type checker.' })
    store.addRoutine(bot.id, { name: 'Documentation review', prompt: 'Check current documentation for the browser integration.', schedule: { kind: 'daily', hour: 8, minute: 0, timeZone: 'America/Fortaleza' } })
    store.addNote(bot.id, 'Codimium is the persistent browser profile used by this agent.', 'user')
    console.log(url)
    const controller = new AbortController(), stop = () => controller.abort()
    process.on('SIGTERM', stop); process.on('SIGINT', stop)
    try { await delay(15 * 60_000, undefined, { signal: controller.signal }) } catch (error) { if (!controller.signal.aborted) throw error }
    process.off('SIGTERM', stop); process.off('SIGINT', stop)
  } else {
    assert.equal((await request('/api/bots')).status, 401)
    const html = await request('/')
    assert.match(html.headers.get('content-security-policy')!, /frame-ancestors 'none'/)
    assert.match(html.headers.get('content-security-policy')!, /script-src 'nonce-/)
    assert.equal(html.headers.get('cache-control'), 'no-store')
    assert.equal((await html.text()).includes(token), false)
    assert.equal((await request('/api/login', { token }, { origin: 'https://outside.example' })).status, 403)
    assert.equal((await request('/api/login', { token: 'incorrect' })).status, 401)
    const login = await request('/api/login', { token })
    assert.equal(login.status, 200)
    assert.match(login.headers.get('set-cookie')!, /HttpOnly; SameSite=Strict/)
    cookie = login.headers.get('set-cookie')!.split(';')[0]!
    assert.equal((await request('/api/bots', undefined, { cookie, host: 'untrusted.example' })).status, 403)
    assert.equal((await request('/api/bots', {}, { cookie, origin: 'null' })).status, 403)
    assert.equal((await request('/api/bots', [], { cookie })).status, 400)
    const bot = await authorized('/api/bots', { name: 'engineer', projectRoot: directory, instructions: 'Prepare observed findings. Render <img src=x onerror=alert(1)> as text.', reviewerModel: 'quality/reviewer-v1' })
    assert.equal(bot.reviewerModel, 'quality/reviewer-v1')
    const reviewerUpdate = await authorized('/api/bots/' + bot.id + '/reviewer-model', { model: 'quality/reviewer-v2' })
    assert.equal(reviewerUpdate.reviewerModel, 'quality/reviewer-v2')
    assert.equal((await authorized('/api/bots/' + bot.id + '/reviewer-model', { model: null })).reviewerModel, undefined)
    const second = await authorized('/api/bots', { name: 'researcher', projectRoot: directory, instructions: 'Research current sources.' })
    assert.equal((await request('/api/groups')).status, 401)
    const group = await authorized('/api/groups', { name: 'HTTP room', botIds: [bot.id, second.id], shareBrowser: false })
    assert.equal((await authorized('/api/groups')).groups.some((item: { id: string }) => item.id === group.id), true)
    assert.deepEqual((await authorized('/api/groups/' + group.id)).group.members.map((member: { botId: string }) => member.botId).sort(), [bot.id, second.id].sort())
    const groupMessage = { message: 'Compare these two approaches.', messageId: 'web-room-task', recipients: [bot.id, second.id] }
    const groupQueued = await authorized('/api/groups/' + group.id + '/messages', groupMessage)
    const repeatedGroupQueued = await authorized('/api/groups/' + group.id + '/messages', groupMessage)
    assert.deepEqual(repeatedGroupQueued.runs.map((run: { id: string }) => run.id), groupQueued.runs.map((run: { id: string }) => run.id))
    assert.equal((await request('/api/groups/' + group.id + '/messages', groupMessage, { cookie: cookie })).status, 202)
    assert.equal((await request('/api/groups/' + group.id + '/messages', { ...groupMessage, recipients: ['outsider'] }, { cookie })).status, 400)
    assert.equal((await request('/api/groups/' + group.id + '/messages', { ...groupMessage, message: 'Changed payload' }, { cookie })).status, 400)
    for (const run of groupQueued.runs as Array<{ id: string }>) store.cancel(run.id)
    const secondRunBaseline = store.listRuns(second.id).length
    assert.deepEqual(await authorized('/api/groups/' + group.id + '/delete', { confirmation: group.name }), { deleted: true })
    const deliveryTargetId = 'delivery-target-fixture', deliveryId = 'delivery-record-fixture'
    store.store.run('INSERT INTO bot_delivery_targets (id,bot_id,url,topics,public_key,created_at) VALUES (?,?,?,?,?,?)', deliveryTargetId, bot.id, 'https://receiver.example/hook', JSON.stringify(['run.completed']), 'fixture-public-key', new Date().toISOString())
    store.store.run("INSERT INTO bot_delivery_outbox (id,bot_id,target_id,event_id,event_type,body,status,attempt,next_at,response_status,last_error,created_at) VALUES (?,?,?,?,?,?,'failed',1,?,500,?,?)", deliveryId, bot.id, deliveryTargetId, 'fixture-event', 'run.completed', '{"payload":{"output":"VERY_PRIVATE_TASK_BODY"}}', Date.now(), 'fixture receiver error', new Date().toISOString())
    const panelDeliveries = await authorized('/api/bots/' + bot.id + '/deliveries')
    assert.equal(panelDeliveries.targets[0].id, deliveryTargetId)
    assert.equal(panelDeliveries.history[0].id, deliveryId)
    assert.equal(Object.hasOwn(panelDeliveries.history[0], 'body'), false, 'the history API exposes metadata, not full run output')
    assert.equal(JSON.stringify(panelDeliveries).includes('VERY_PRIVATE_TASK_BODY'), false)
    const retriedDelivery = await authorized('/api/bots/' + bot.id + '/deliveries/' + deliveryId + '/retry', {})
    assert.equal(retriedDelivery.status, 'queued')
    assert.equal(Object.hasOwn(retriedDelivery, 'body'), false)
    assert.equal((await request('/api/bots/' + bot.id + '/deliveries', { url: 'https://127.0.0.1/hook', topics: ['run.completed'] }, { cookie })).status, 400)
    const eventBot = await authorized('/api/bots', { name: 'event-consumer', projectRoot: directory, instructions: 'Handle authorized external event notifications.' })
    const lifecycleBot = await authorized('/api/bots', { name: 'lifecycle-check', projectRoot: directory, instructions: 'Disposable bot for export and deletion checks.' })
    const lifecycleHook = await authorized('/api/bots/' + lifecycleBot.id + '/webhooks/issues.opened', {})
    store.addNote(lifecycleBot.id, 'Exported private note.', 'user:fixture')
    assert.equal((await request('/api/bots/' + lifecycleBot.id + '/export')).status, 401)
    const exportResponse = await request('/api/bots/' + lifecycleBot.id + '/export', undefined, { cookie })
    assert.equal(exportResponse.status, 200)
    assert.match(exportResponse.headers.get('content-disposition')!, /attachment; filename=/)
    const exported = await exportResponse.json() as { bot: { id: string }; notes: Array<{ content: string }> }
    assert.equal(exported.bot.id, lifecycleBot.id)
    assert.ok(exported.notes.some(note => note.content === 'Exported private note.'))
    assert.equal(JSON.stringify(exported).includes(lifecycleHook.secret), false)
    assert.equal((await request('/api/bots/' + lifecycleBot.id + '/delete', { confirmation: 'wrong' }, { cookie })).status, 400)
    assert.deepEqual(await authorized('/api/bots/' + lifecycleBot.id + '/delete', { confirmation: lifecycleBot.name }), { deleted: true, filesRemoved: true })
    assert.equal((await authorized('/api/bots')).bots.some((entry: { id: string }) => entry.id === lifecycleBot.id), false)
    await authorized('/api/bots/' + eventBot.id + '/routines', { name: 'Issue alerts', prompt: 'Review the incoming issue.', schedule: { kind: 'event', topic: 'issue.opened' }, occurrenceId: 'web-event-routine' })
    await authorized('/api/bots/' + second.id + '/routines', { name: 'Separate issue alerts', prompt: 'Review the issue privately.', schedule: { kind: 'event', topic: 'issue.opened' }, occurrenceId: 'web-event-routine-other' })
    const eventPath = '/api/bots/' + eventBot.id + '/events/issue.opened', eventData = { eventId: 'issue-42', payload: { title: 'Bug', api_key: 'event-secret-value', fields: { z: 1, a: true } } }
    const hook = await authorized('/api/bots/' + eventBot.id + '/webhooks/issue.opened', {})
    assert.match(hook.secret, /^dsk_hook_[A-Za-z0-9_-]{43}$/)
    assert.equal(JSON.stringify(store.store.query('SELECT * FROM bot_webhook_credentials')).includes(hook.secret), false)
    const listedHooks = await authorized('/api/bots/' + eventBot.id + '/webhooks')
    assert.deepEqual(listedHooks.map(({ botId, topic }: any) => ({ botId, topic })), [{ botId: eventBot.id, topic: 'issue.opened' }])
    assert.equal(typeof listedHooks[0].createdAt, 'string')
    assert.equal((await request('/api/bots/' + eventBot.id + '/webhooks/issue.opened/revoke', {})).status, 401)
    const rotatedHook = await authorized('/api/bots/' + eventBot.id + '/webhooks/issue.opened', {})
    assert.notEqual(rotatedHook.secret, hook.secret)
    const sendEvent = (data: unknown, headers: Record<string, string> = {}, credential = rotatedHook.secret) => fetch(url + eventPath, { method: 'POST', headers: { authorization: 'Bearer ' + credential, 'content-type': 'application/json', ...headers }, body: JSON.stringify(data) })
    assert.equal((await request(eventPath, eventData)).status, 401)
    assert.equal((await request(eventPath, eventData, { cookie })).status, 401)
    assert.equal((await sendEvent(eventData, {}, token)).status, 401)
    assert.equal((await sendEvent(eventData, {}, hook.secret)).status, 401)
    assert.equal((await sendEvent(eventData, { origin: 'https://outside.example' })).status, 403)
    assert.equal((await fetch(url + '/api/bots/' + eventBot.id + '/events/issue.closed', { method: 'POST', headers: { authorization: 'Bearer ' + rotatedHook.secret, 'content-type': 'application/json' }, body: JSON.stringify(eventData) })).status, 401)
    assert.equal((await sendEvent({ eventId: 'missing-payload' })).status, 400)
    const delivered = await sendEvent(eventData)
    assert.equal(delivered.status, 202)
    const delivery = await delivered.json() as { botId: string; topic: string; eventId: string; runIds: string[] }
    assert.deepEqual(delivery, { botId: eventBot.id, topic: 'issue.opened', eventId: 'issue-42', runIds: store.listRuns(eventBot.id).map(run => run.id) })
    assert.equal(delivery.runIds.length, 1)
    const replay = await sendEvent({ eventId: 'issue-42', payload: { fields: { a: true, z: 1 }, api_key: 'rotated-secret', title: 'Bug' } })
    assert.equal(replay.status, 202)
    assert.deepEqual(await replay.json(), delivery)
    assert.equal(store.listRuns(eventBot.id).length, 1)
    assert.equal(store.listRuns(eventBot.id)[0]!.prompt.includes('event-secret-value'), false)
    assert.equal((await sendEvent({ eventId: 'issue-42', payload: { title: 'Changed' } })).status, 400)
    assert.equal((await sendEvent({ eventId: 'too-large', payload: { text: 'x'.repeat(64 * 1024) } })).status, 400)
    const secondHook = await authorized('/api/bots/' + second.id + '/webhooks/issue.opened', {})
    assert.equal((await fetch(url + '/api/bots/' + second.id + '/events/issue.opened', { method: 'POST', headers: { authorization: 'Bearer ' + rotatedHook.secret, 'content-type': 'application/json' }, body: JSON.stringify(eventData) })).status, 401)
    const separateScope = await fetch(url + '/api/bots/' + second.id + '/events/issue.opened', { method: 'POST', headers: { authorization: 'Bearer ' + secondHook.secret, 'content-type': 'application/json' }, body: JSON.stringify(eventData) })
    assert.equal(separateScope.status, 202)
    const secondDelivery = await separateScope.json() as { runIds: string[] }
    assert.equal(secondDelivery.runIds.length, 1)
    assert.equal(store.listRuns(second.id).length, secondRunBaseline + 1)
    const secondEventPath = '/api/bots/' + second.id + '/events/issue.opened'
    const signedRawBody = JSON.stringify(eventData)
    const signingSeed = Buffer.from(secondHook.secret.slice('dsk_hook_'.length), 'base64url')
    const signingKey = createPrivateKey({ key: Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), signingSeed]), format: 'der', type: 'pkcs8' })
    const signedHeader = 'ed25519=' + sign(null, Buffer.from(signedRawBody), signingKey).toString('base64url')
    const signedDelivery = (rawBody: string, signature: string) => fetch(url + secondEventPath, { method: 'POST', headers: { 'content-type': 'application/json', 'x-deepseek-signature': signature }, body: rawBody })
    assert.equal((await signedDelivery(signedRawBody + ' ', signedHeader)).status, 401, 'the signature binds the exact raw body')
    const signedReplay = await signedDelivery(signedRawBody, signedHeader)
    assert.equal(signedReplay.status, 202, 'a signed machine request needs no panel token or bearer header')
    assert.deepEqual((await signedReplay.json() as any).runIds, secondDelivery.runIds, 'the original event receipt remains idempotent')

    const limitedBot = await authorized('/api/bots', { name: 'rate-limited', projectRoot: directory, instructions: 'Handle bounded event load.' })
    await authorized('/api/bots/' + limitedBot.id + '/routines', { name: 'Rate-limited events', prompt: 'Review the event.', schedule: { kind: 'event', topic: 'test.rate' }, occurrenceId: 'rate-event-routine' })
    const limitedHook = await authorized('/api/bots/' + limitedBot.id + '/webhooks/test.rate', {})
    const limitedServer = startBotWebServer(store, { token, port: 0, webhookRateLimit: { maxEvents: 1, windowMs: 1000 } })
    try {
      const limitedPath = '/api/bots/' + limitedBot.id + '/events/test.rate'
      const limitedRequest = (raw: string) => fetch(limitedServer.url + limitedPath, { method: 'POST', headers: { authorization: 'Bearer ' + limitedHook.secret, 'content-type': 'application/json' }, body: raw })
      const firstRaw = JSON.stringify({ eventId: 'limited-one', payload: { value: 1 } })
      const firstRateLimited = await limitedRequest(firstRaw)
      assert.equal(firstRateLimited.status, 202)
      const firstRateBody = await firstRateLimited.json() as { runIds: string[] }
      const duplicateRateLimited = await limitedRequest(firstRaw)
      assert.equal(duplicateRateLimited.status, 202, 'an exact retry does not consume another rate slot')
      assert.deepEqual((await duplicateRateLimited.json() as any).runIds, firstRateBody.runIds)
      const secondRaw = JSON.stringify({ eventId: 'limited-two', payload: { value: 2 } })
      const blockedByLimit = await limitedRequest(secondRaw)
      assert.equal(blockedByLimit.status, 429)
      assert.equal(blockedByLimit.headers.get('retry-after'), '1')
      assert.equal((await blockedByLimit.json() as any).code, 'bot_event_rate_limited')
      await delay(1050)
      assert.equal((await limitedRequest(secondRaw)).status, 202, 'an unaccepted event can be retried after the durable rate window')
    } finally { limitedServer.server.stop(true) }
    for (let index = 0; index < 255; index++) store.dispatchEvent('issue.opened', 'queue-fill-' + index, { index }, eventBot.id)
    assert.equal((await sendEvent(eventData)).status, 202, 'a duplicate remains idempotent when the queue is full')
    const saturated = { eventId: 'queue-at-capacity', payload: {} }
    const fullQueue = await sendEvent(saturated)
    assert.equal(fullQueue.status, 429)
    assert.equal(fullQueue.headers.get('retry-after'), '10')
    assert.equal((await fullQueue.json() as any).code, 'bot_event_queue_full')
    const oldest = store.claim(eventBot.id, 'event-drain-worker')!
    store.finish(oldest.id, 'event-drain-worker', 'completed', 'Fixture event processed')
    store.acknowledgeStop(oldest.id, 'event-drain-worker')
    assert.equal((await sendEvent(saturated)).status, 202, 'the same unaccepted event can be retried after capacity returns')
    assert.equal((await request('/api/bots/' + eventBot.id + '/webhooks/issue.opened/revoke', {}, { cookie })).status, 200)
    assert.equal((await sendEvent({ eventId: 'after-revoke', payload: {} })).status, 401)
    const note = await authorized('/api/bots/' + bot.id + '/notes', { content: 'HTTP saved fact', source: 'user:fixture' })
    assert.equal((await request('/api/bots/' + bot.id + '/notes/' + note.id, { content: 'No authentication', source: 'fixture', version: note.version })).status, 401)
    assert.equal((await request('/api/bots/' + bot.id + '/notes/' + note.id, { content: 'Foreign origin', source: 'fixture', version: note.version }, { cookie, origin: 'https://outside.example' })).status, 403)
    assert.equal((await request('/api/bots/' + second.id + '/notes/' + note.id, { content: 'Wrong bot', source: 'fixture', version: note.version }, { cookie })).status, 400)
    assert.equal((await request('/api/bots/' + bot.id + '/notes/' + note.id, { content: 'Safe fact', source: 'fixture', version: '1' }, { cookie })).status, 400)
    assert.equal((await request('/api/bots/' + bot.id + '/notes/' + note.id, { content: 'password=fixture-only-value', source: 'fixture', version: note.version }, { cookie })).status, 400)
    assert.equal((await authorized('/api/bots/' + bot.id + '/notes/' + note.id + '/remove', { version: note.version })).removed, true)
    const input = { message: 'Inspect the browser lifecycle.', occurrenceId: 'web-message-one' }
    const job = await authorized('/api/bots/' + bot.id + '/messages', input)
    assert.equal((await authorized('/api/bots/' + bot.id + '/messages', input)).id, job.id)
    assert.equal((await request('/api/bots/' + bot.id + '/messages', { ...input, message: 'Changed request' }, { cookie })).status, 400)
    store.claim(bot.id, 'check-worker')
    store.checkpoint(job.id, 'check-worker', [{ role: 'user', content: 'Inspect the browser lifecycle.' }])
    const perRunTranscript = await authorized('/api/runs/' + job.id + '/transcript')
    assert.equal(perRunTranscript.messages[0].content, 'Inspect the browser lifecycle.')
    assert.equal((await authorized('/api/bots/' + bot.id)).legacyTranscript.length, 0)
    const decision = store.requestDecision(job.id, 'check-worker', 'permission', { toolName: 'shell', args: { command: 'printf approved' } })
    assert.equal((await request('/api/decisions/' + decision.id, { fingerprint: 'changed', answer: 'once' }, { cookie })).status, 400)
    await authorized('/api/decisions/' + decision.id, { fingerprint: decision.fingerprint, answer: 'once' })
    assert.equal(store.consumeDecision(decision.id, 'check-worker'), 'once')
    assert.equal((await request('/api/decisions/' + decision.id, { fingerprint: decision.fingerprint, answer: 'once' }, { cookie })).status, 400)
    store.beginAction(job.id, 'check-worker', 'shell', { command: 'printf effect' }, false)
    store.recover(Date.now() + 31_000)
    assert.equal((await request('/api/runs/' + job.id + '/retry', { reconciled: true }, { cookie })).status, 400)
    await authorized('/api/runs/' + job.id + '/reconcile', { evidence: 'Verified that the proposed effect did not happen.' })
    await authorized('/api/runs/' + job.id + '/retry', { reconciled: true })
    const routine = { name: 'Daily review', prompt: 'Check current sources.', schedule: { kind: 'daily', hour: 8, minute: 0, timeZone: 'America/Fortaleza' }, occurrenceId: 'web-routine-one' }
    const saved = await authorized('/api/bots/' + bot.id + '/routines', routine)
    assert.equal((await authorized('/api/bots/' + bot.id + '/routines', routine)).id, saved.id)
    assert.equal(saved.version, 1)
    const editPayload = { name: 'Weekly review', prompt: 'Check current sources and report the delta.', schedule: { kind: 'interval', everyMs: 120_000 }, version: saved.version }
    const editedRoutine = await authorized('/api/bots/' + bot.id + '/routines/' + saved.id, editPayload)
    assert.equal(editedRoutine.version, 2)
    assert.equal(editedRoutine.schedule.everyMs, 120_000)
    assert.deepEqual(await authorized('/api/bots/' + bot.id + '/routines/' + saved.id, { ...editPayload, version: 1 }), editedRoutine)
    assert.equal((await request('/api/bots/' + bot.id + '/routines/' + saved.id, { ...editPayload, prompt: 'Stale edit' }, { cookie })).status, 400)
    assert.equal((await request('/api/bots/' + bot.id + '/routines/' + saved.id, { enabled: false, version: 1 }, { cookie })).status, 400)
    const pausedRoutine = await authorized('/api/bots/' + bot.id + '/routines/' + saved.id, { enabled: false, version: 2 })
    assert.equal(pausedRoutine.version, 3)
    assert.equal(pausedRoutine.enabled, false)
    const manualRun = await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/run', { occurrenceId: 'web-manual-run-1' })
    assert.equal(manualRun.status, 'queued')
    assert.equal(manualRun.source, `routine-manual:${saved.id}:v3`)
    assert.equal((await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/run', { occurrenceId: 'web-manual-run-1' })).id, manualRun.id)
    assert.equal((await request('/api/bots/' + bot.id + '/routines/' + saved.id + '/test', { occurrenceId: 'unauth-safe-test' })).status, 401)
    const scheduleBeforeTest = store.routines(bot.id).find(item => item.id === saved.id)
    const safeTest = await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/test', { occurrenceId: 'web-safe-test-1' })
    assert.equal(safeTest.testMode, true)
    assert.equal(safeTest.source, `routine-test:${saved.id}:v3`)
    assert.deepEqual(store.routines(bot.id).find(item => item.id === saved.id), scheduleBeforeTest)
    assert.equal((await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/test', { occurrenceId: 'web-safe-test-1' })).id, safeTest.id)
    assert.deepEqual((await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/runs')).map((run: { id: string }) => run.id), [safeTest.id, manualRun.id])
    assert.equal((await request('/api/bots/' + bot.id + '/routines/' + saved.id + '/delete', { version: 2 }, { cookie })).status, 400)
    assert.equal((await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/delete', { version: 3 })).deleted, true)
    assert.equal(store.getRun(manualRun.id).status, 'queued')
    store.cancel(manualRun.id)
    assert.deepEqual((await authorized('/api/bots/' + bot.id + '/routines/' + saved.id + '/runs')).map((run: { id: string }) => run.id), [safeTest.id, manualRun.id])
    assert.equal((await request('/api/bots/' + bot.id + '/routines', { name: 'Expired', prompt: 'Never silently skip', schedule: { kind: 'once', at: Date.now() - 1 }, occurrenceId: 'web-expired-once' }, { cookie })).status, 400)
    assert.equal((await request('/api/bots/' + second.id + '/routines/' + saved.id, { enabled: false }, { cookie })).status, 400)
    await authorized('/api/runs/' + job.id + '/cancel', {})
    assert.equal(store.getRun(job.id).status, 'cancelled')
    assert.equal(store.routines(bot.id).some(item => item.id === saved.id), false)
    store.cancel(safeTest.id)
    const demonstration = store.enqueue(bot.id, 'Demonstrated browser procedure')
    store.claim(bot.id, 'procedure-worker')
    store.recordBrowserStep(demonstration.id, 'procedure-worker', { action: 'navigate', url: 'https://example.com/form' }, 'about:blank')
    store.recordBrowserStep(demonstration.id, 'procedure-worker', { action: 'type', role: 'textbox', name: 'Message', value: 'web-demonstration-value' }, 'https://example.com/form')
    store.recordBrowserStep(demonstration.id, 'procedure-worker', { action: 'expect', text: 'Observed demonstration outcome' }, 'https://example.com/form')
    assert.equal((await request('/api/bots/' + bot.id + '/procedures', { runId: demonstration.id, name: 'web-source' }, { cookie })).status, 400)
    store.checkpoint(demonstration.id, 'procedure-worker', []); store.finish(demonstration.id, 'procedure-worker', 'completed', 'Observed')
    store.acknowledgeStop(demonstration.id, 'procedure-worker')
    const learned = await authorized('/api/bots/' + bot.id + '/procedures', { runId: demonstration.id, name: 'web-source' })
    assert.equal((await authorized('/api/bots/' + bot.id + '/procedures', { runId: demonstration.id, name: 'web-source' })).id, learned.id)
    const manifest = await request('/api/bots/' + bot.id + '/procedures/' + learned.id, undefined, { cookie })
    assert.match(manifest.headers.get('content-disposition')!, /SKILL.md/)
    assert.equal((await manifest.text()).includes('web-demonstration-value'), false)
    assert.equal((await request('/api/bots/' + second.id + '/procedures/' + learned.id, undefined, { cookie })).status, 400)
    await authorized('/api/bots/' + bot.id + '/enabled', { enabled: false })
    assert.equal(store.getBot(bot.id).enabled, false)
    const events = await authorized('/api/bots/' + bot.id + '/events?after=0')
    assert.ok(events.some((event: any) => event.type === 'BotDecisionRequired'))
    assert.deepEqual(await authorized('/api/bots/' + bot.id + '/events?after=' + events.at(-1).event_seq), [])
    assert.equal((await request('/api/bots/' + bot.id + '/events?after=-1', undefined, { cookie })).status, 400)
    await authorized('/api/logout', {})
    assert.equal((await request('/api/bots', undefined, { cookie })).status, 401)
    assert.equal((await request('/api/bots', undefined, { authorization: 'Bearer ' + token })).status, 200)
    assert.equal((await request('/api/bots', {}, { authorization: 'Bearer ' + token, origin: 'https://outside.example' })).status, 403)
    if (findChromium() && process.platform !== 'win32') {
      const browser = new BrowserService(), key = contextKey('panel-check')
      try {
        await browser.withTab(key, async () => {})
        browser.approve(key, url)
        await browser.withTab(key, async tab => {
          await tab.navigate(url)
          await tab.settle()
          const evaluate = async <T>(expression: string) => {
            const { result, exceptionDetails } = await tab.cdp.send<{ result: { value: T }; exceptionDetails?: unknown }>('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }, tab.sessionId)
            assert.equal(exceptionDetails, undefined)
            return result.value
          }
          const until = async (expression: string) => {
            for (let attempt = 0; attempt < 100; attempt++) { if (await evaluate(expression)) return; await delay(50) }
            throw new Error('Panel UI did not reach: ' + expression + '; ' + await evaluate("JSON.stringify({notice:document.getElementById('notice').textContent,error:document.getElementById('login-error').textContent,agent:document.getElementById('bot-name').textContent})") + '; logs=' + JSON.stringify(tab.drainLogs(true)))
          }
          // Fixed, test-authored DOM operations exercise the bundled script and native form events.
          await evaluate(`document.getElementById('token').value=${JSON.stringify(token)};document.getElementById('login-form').requestSubmit();true`)
          await until("!document.getElementById('app').hidden && document.getElementById('bot-name').textContent === 'engineer'")
          assert.equal(await evaluate("document.querySelectorAll('#responsibility img').length"), 0)
          assert.equal(await evaluate("document.getElementById('token').value"), '')
          await evaluate("(()=>{document.getElementById('new-note').click();const form=document.getElementById('note-form');form.elements.content.value='Memory from UI <img src=x onerror=alert(1)>';form.requestSubmit();return true})()")
          await until("!document.getElementById('note-dialog').open && document.getElementById('notes').textContent.includes('Memory from UI')")
          let panelNote = store.notes(bot.id).find(n => n.content.startsWith('Memory from UI'))!
          assert.equal(panelNote.version, 1); assert.equal(await evaluate("document.querySelectorAll('#notes img').length"), 0)
          await evaluate("document.querySelector('#notes button').click();document.getElementById('note-form').elements.content.value='Corrected memory from panel';document.getElementById('note-form').requestSubmit();true")
          await until("!document.getElementById('note-dialog').open && document.getElementById('notes').textContent.includes('Corrected memory from panel')")
          panelNote = store.notes(bot.id).find(n => n.id === panelNote.id)!
          assert.equal(panelNote.version, 2)
          await evaluate("document.querySelector('#notes button').click();true")
          store.updateNote(bot.id, panelNote.id, 'Concurrent memory correction', 'user:fixture', null, panelNote.version)
          await evaluate("document.getElementById('note-form').elements.content.value='Stale form value';document.getElementById('note-form').requestSubmit();true")
          await until("document.getElementById('note-dialog').open && document.querySelector('#note-form .error').textContent.includes('stale')")
          assert.equal(store.notes(bot.id).find(n => n.id === panelNote.id)!.content, 'Concurrent memory correction')
          await evaluate("document.querySelector('#note-form [data-close]').click();refresh().then(()=>true)")
          await until("document.getElementById('notes').textContent.includes('Concurrent memory correction')")
          await evaluate("document.querySelector('#notes button').click();document.getElementById('remove-note').click();true")
          await until("!document.getElementById('note-dialog').open && !document.getElementById('notes').textContent.includes('Concurrent memory correction')")
          assert.equal(store.notes(bot.id).some(n => n.id === panelNote.id), false)
          await evaluate("document.getElementById('message').value='Task from the real panel UI';document.getElementById('composer').requestSubmit();true")
          await until("document.getElementById('message').value === ''")
          assert.equal(store.listRuns(bot.id).filter(run => run.prompt === 'Task from the real panel UI').length, 1)
          store.setEnabled(bot.id, true)
          const active = store.claim(bot.id, 'panel-guide-worker')!
          assert.equal(active.prompt, 'Task from the real panel UI')
          await evaluate("refresh().then(()=>true)")
          await until("[...document.querySelectorAll('#feed button')].some(b=>b.textContent==='Guide task')")
          await evaluate("[...document.querySelectorAll('#feed button')].find(b=>b.textContent==='Guide task').click();document.getElementById('guide-form').elements.message.value='Current task guidance <img src=x onerror=alert(1)>';document.getElementById('guide-form').requestSubmit();true")
          await until("!document.getElementById('guide-dialog').open && document.getElementById('feed').textContent.includes('Current task guidance')")
          assert.equal(store.steeringMessages(active.id).length, 1)
          assert.equal(store.steeringMessages(active.id)[0]!.content, 'Current task guidance <img src=x onerror=alert(1)>')
          assert.equal(await evaluate("document.querySelectorAll('#feed img').length"), 0)
          assert.equal(store.listRuns(bot.id).filter(run => run.prompt === active.prompt).length, 1)
          assert.equal((await request('/api/runs/' + active.id + '/messages', { message: 'No authentication', messageId: 'no-auth' })).status, 401)
          assert.equal((await request('/api/runs/' + active.id + '/messages', { message: 'Wrong origin', messageId: 'wrong-origin' }, { cookie, origin: 'https://outside.example' })).status, 403)
          store.cancel(active.id); store.acknowledgeStop(active.id, 'panel-guide-worker')
          await evaluate("[...document.querySelectorAll('#feed button')].find(b=>b.textContent==='Learn browser skill').click();document.getElementById('learn-form').elements.name.value='from-panel';document.getElementById('learn-form').requestSubmit();true")
          await until("!document.getElementById('learn-dialog').open && document.getElementById('procedures').textContent.includes('from-panel')")
          const panelSkill = store.procedures(bot.id).find(p => p.name === 'from-panel')!
          assert.equal(panelSkill.sourceRunId, demonstration.id)
          const panelEndsAt = Math.ceil((Date.now() + 48 * 60 * 60_000) / 60_000) * 60_000
          await evaluate(`document.getElementById('new-routine').click();const f=document.getElementById('routine-form');f.elements.name.value='Learned routine from panel';f.elements.prompt.value='Run the observed browser procedure';f.elements.endsAt.value=localDateTime(${panelEndsAt});f.elements.procedureId.value=${JSON.stringify(panelSkill.id)};f.elements.procedureId.dispatchEvent(new Event('change'));f.elements['procedure:input2'].value='New message';f.elements['procedure:expectedText3'].value='Observed current outcome';f.requestSubmit();true`)
          await until("!document.getElementById('routine-dialog').open && document.getElementById('routines').textContent.includes('Learned routine from panel')")
          const panelRoutine = store.routines(bot.id).find(r => r.name === 'Learned routine from panel')!
          assert.equal(panelRoutine.procedureId, panelSkill.id)
          assert.deepEqual(panelRoutine.procedureInputs, { input2: 'New message', expectedText3: 'Observed current outcome' })
          assert.equal('endsAt' in panelRoutine.schedule ? panelRoutine.schedule.endsAt : undefined, panelEndsAt)
          await evaluate("[...document.querySelectorAll('#routines .routine')].find(el=>el.textContent.includes('Learned routine from panel')).querySelector('button').click();true")
          await until("document.getElementById('feed').textContent.includes('Safe test · queued')")
          const panelSafeRun = store.routineRuns(bot.id, panelRoutine.id).find(run => run.testMode)!
          assert.ok(panelSafeRun)
          assert.equal(panelSafeRun.procedureId, panelSkill.id)
          await evaluate("Array.from([...document.querySelectorAll('#routines .routine')].find(el=>el.textContent.includes('Learned routine from panel')).querySelectorAll('button')).find(b=>b.textContent==='Edit routine').click();true")
          await until("document.getElementById('routine-dialog').open && document.getElementById('routine-title').textContent==='Edit routine'")
          await evaluate("(()=>{const f=document.getElementById('routine-form');f.elements.name.value='Edited routine from panel';f.elements.prompt.value='Use the revised browser task';f.requestSubmit();return true})()")
          await until("!document.getElementById('routine-dialog').open && document.getElementById('routines').textContent.includes('Edited routine from panel')")
          assert.equal(store.routines(bot.id).find(r => r.id === panelRoutine.id)?.version, 2)
          await evaluate("window.confirm=()=>true;[...document.querySelectorAll('#routines .routine')].find(el=>el.textContent.includes('Edited routine from panel')).querySelector('button').click();true")
          await until("document.getElementById('feed').textContent.includes('Use the revised browser task')")
          const uiManualRun = store.routineRuns(bot.id, panelRoutine.id)[0]!
          assert.equal(uiManualRun.procedureId, panelSkill.id)
          await evaluate("Array.from([...document.querySelectorAll('#routines .routine')].find(el=>el.textContent.includes('Edited routine from panel')).querySelectorAll('button')).find(b=>b.textContent==='Delete routine').click();true")
          await until("!document.getElementById('routines').textContent.includes('Edited routine from panel')")
          assert.equal(store.getRun(uiManualRun.id).status, 'queued')
          store.cancel(uiManualRun.id)
          await tab.cdp.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true }, tab.sessionId)
          assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'), true)
          assert.equal(await evaluate("getComputedStyle(document.querySelector('.layout')).flexDirection"), 'column')
          assert.deepEqual(tab.drainLogs(true).filter(entry => entry.level === 'error').map(entry => entry.text), [])
          // Expiry must clear open dialogs and sensitive DOM state, not merely hide the main panel.
          await evaluate("document.getElementById('message').value='private draft';document.getElementById('browser-input').value='human-only text';document.getElementById('browser-image').src='data:image/jpeg;base64,AAAA';document.getElementById('learn-dialog').showModal();true")
          await evaluate("fetch('/api/logout',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}).then(()=>refresh()).then(()=>true)")
          await until("!document.getElementById('login').hidden && document.getElementById('app').hidden")
          assert.equal(await evaluate("document.querySelectorAll('dialog[open]').length"), 0)
          assert.equal(await evaluate("document.getElementById('browser-input').value"), '')
          assert.equal(await evaluate("document.getElementById('browser-image').hasAttribute('src')"), false)
          assert.equal(await evaluate("document.getElementById('message').value"), '')
          assert.equal(await evaluate("document.getElementById('note-form').elements.content.value"), '')
          assert.equal(await evaluate("document.getElementById('feed').textContent"), '')
          await evaluate(`document.getElementById('token').value=${JSON.stringify(token)};document.getElementById('login-form').requestSubmit();true`)
          await until("!document.getElementById('app').hidden && document.getElementById('bot-name').textContent === 'engineer'")
          await evaluate("document.getElementById('message').value='draft before logout';document.getElementById('routine-dialog').showModal();true")
          await evaluate("document.getElementById('logout').click();true")
          await until("!document.getElementById('login').hidden && document.getElementById('app').hidden")
          assert.equal(await evaluate("document.querySelectorAll('dialog[open]').length"), 0)
          assert.equal(await evaluate("document.getElementById('message').value"), '')
        })
      } finally { await browser.shutdown(); await browser.whenClosed() }
    }
    for (let attempt = 0; attempt < 10; attempt++) assert.equal((await request('/api/login', { token: 'incorrect' })).status, 401)
    assert.equal((await request('/api/login', { token })).status, 429)
    console.log('Bot web check passed: real HTTP, authentication, host/origin checks, signed webhook delivery, rate limits, exact approvals, idempotent queue/routines, reconciliation, cancellation and logout.')
  }
} finally { server.stop(true); store.close(); await rm(directory, { recursive: true, force: true }) }
