import { readFileSync, writeFileSync } from 'node:fs'

// Vendored browser asset: dev and packaged CLI both work without a CDN or runtime bundler.
const result = await Bun.build({ entrypoints: ['src/bots/pod-avatar-scene.ts'], target: 'browser', format: 'iife', minify: true })
if (!result.success) throw new Error(result.logs.join('\n'))
const source = ('/* Three.js license: ' + readFileSync('node_modules/three/LICENSE', 'utf8') + ' */\n' + await result.outputs[0].text()).replace(/<\/script/gi, '<\\/script')
writeFileSync('src/bots/pod-avatar-runtime.ts', '// Generated by bun scripts/build-pod-avatar.ts; do not edit. Includes Three.js (MIT).\nexport const POD_AVATAR_RUNTIME = ' + JSON.stringify(source) + '\n')
